export const Areas = {
  ANCIENT: {
    A_SITE: "A Site",
    A_MAIN: "A Main",
    YARD: "Yard",
    T_SPAWN: "T Spawn",
    TEMPLE: "Temple",
    TRIPLE: "Triple",
    HOUSE: "House",
    MID: "Mid",
    ELBOW: "Elbow",
    DONUT: "Donut",
    WINDOW: "Window",
    CATWALK: "Catwalk",
    B_RAMP: "B Ramp",
    B_SITE: "B Site",
    CAVE: "Cave",
    B_SHORT: "B Short",
    B_LONG: "B Long",
    CT_SPAWN: "CT Spawn",
    LANE: "Lane",
    RUINS: "Ruins",
    ALLEY: "Alley",
  },
  NUKE: {
    A_SITE: "A Site",
    HUT: "Hut",
    TROPHY: "Trophy",
    SILO: "Silo",
    ROOF: "Roof",
    SQUEAKY: "Squeaky",
    OUTSIDE: "Outside",
    RED_BOX: "Red Box",
    SECRET: "Secret",
    GARAGE: "Garage",
    HELL: "Hell",
    B_RAMP: "B Ramp",
    DARK: "Dark",
    B_SITE: "B Site",
    BACK_HALLS: "Back Halls",
    T_SPAWN: "T Spawn",
    CT_SPAWN: "CT Spawn",
    LOBBY: "Lobby",
    HEAVEN: "Heaven",
  },
  MIRAGE: {
    A_SITE: "A Site",
    A_RAMP: "A Ramp",
    T_ROOF: "T Roof",
    PALACE: "Palace",
    CT: "CT",
    CT_SPAWN: "CT Spawn",
    MID: "Mid",
    CONNECTOR: "Connector",
    LADDER_ROOM: "Ladder Room",
    CATWALK: "Catwalk",
    B_SHORT: "B Short",
    APARTMENTS: "Apartments",
    B_SITE: "B Site",
    MARKET: "Market",
    T_SPAWN: "T Spawn",
    TOP_MID: "Top Mid",
  },
  INFERNO: {
    A_SITE: "A Site",
    A_SHORT: "A Short",
    APARTMENTS: "Apartments",
    A_LONG: "A Long",
    SECOND_MID: "2nd Mid",
    T_APARTMENTS: "T Apartments",
    B_SITE: "B Site",
    TREE: "Tree",
    CT: "CT",
    BANANA: "Banana",
    T_RAMP: "T Ramp",
    T_SPAWN: "T Spawn",
    MID: "Mid",
    CT_SPAWN: "CT Spawn",
  },
  OVERPASS: {
    A_SITE: "A Site",
    A_SHORT: "A Short",
    A_LONG: "A Long",
    MID: "Mid",
    CONNECTOR: "Connector",
    BATHROOMS: "Bathrooms",
    B_SHORT: "B Short",
    WATER: "Water",
    MONSTER: "Monster",
    CANALS: "Canals",
    B_SITE: "B Site",
    GRAFFITI: "Graffiti",
    T_SPAWN: "T Spawn",
    CT_SPAWN: "CT Spawn",
    HEAVEN: "Heaven",
  },
  VERTIGO: {
    A_SITE: "A Site",
    A_RAMP: "A Ramp",
    SANDBAG: "Sandbag",
    HEADSHOT: "Headshot",
    HEAVEN: "Heaven",
    ELEVATOR: "Elevator",
    MID: "Mid",
    T_MID: "T Mid",
    B_SITE: "B Site",
    B_MAIN: "B Main",
    B_STAIRS: "B Stairs",
    WHITE_BOX: "White box",
    CT_SPAWN: "CT Spawn",
    T_SPAWN: "T Spawn",
  }
}