import { Grenade } from "./grenade";

// TODO: All the id's in here are being used. Every filename without an ID should be deleted.

export const GRENADES: Grenade[] = [
    // *********************************************** OVERPASS ***********************************************

    { id: "overpass_a_execute_combo_from_short", title: "A execute nades", startingLocation: "divider", nadeType: "smoke, molly, flash", 
    throwType: "normal, jump", side: "T", description: "Use this to execute A.", map: "overpass", contentUrl: "https://streamable.com/l/w4z08t/mp4.mp4"},
    { id: "overpass_smoke_bank_from_outside_connector", title: "Smoke bank", startingLocation: "outside connector", nadeType: "smoke", 
    throwType: "jump", side: "T", description: "", map: "overpass", contentUrl: "https://streamable.com/l/3e0k0p/mp4.mp4"},
    { id: "overpass_anti_eco_a_utility", title: "Anti-eco utility for A", startingLocation: "CT spawn", nadeType: "molly, flash", 
    throwType: "normal, jump", side: "CT", description: "", map: "overpass", contentUrl: "https://streamable.com/l/jskaxw/mp4.mp4"},
    { id: "overpass_molly_toxic_for_real", title: "Molly toxic", startingLocation: "canals", nadeType: "molly", 
    throwType: "forward jump", side: "T", description: "This is a forward+jump throw.", map: "overpass", contentUrl: "https://streamable.com/l/177ygl/mp4.mp4"},
    { id: "overpass_support_flash_monster", title: "Support flash monster", startingLocation: "heaven", nadeType: "flash", 
    throwType: "run", side: "CT", description: "", map: "overpass", contentUrl: "https://streamable.com/l/48i8fc/mp4.mp4"},
    { id: "overpass_support_flash_b_from_a", title: "Support flash B", startingLocation: "CT spawn", nadeType: "flash", 
    throwType: "run", side: "CT", description: "", map: "overpass", contentUrl: "https://streamable.com/l/m1rer5/mp4.mp4"},
    { id: "overpass_support_flash_over_monster", title: "Support flash over monster", startingLocation: "canals", nadeType: "flash", 
    throwType: "normal", side: "T", description: "", map: "overpass", contentUrl: "https://streamable.com/l/t6u3i5/mp4.mp4"},
    { id: "overpass_support_flash_mid", title: "Support flash mid", startingLocation: "outside bathrooms", nadeType: "flash", 
    throwType: "normal", side: "CT", description: "", map: "overpass", contentUrl: "https://streamable.com/l/1nhpgl/mp4.mp4"},
    { id: "overpass_support_flash_deep_monster", title: "Support flash deep monster", startingLocation: "headshot", nadeType: "flash", 
    throwType: "jump", side: "CT", description: "", map: "overpass", contentUrl: "https://streamable.com/l/fsyd7d/mp4.mp4"},
    { id: "overpass_wallbang_door", title: "Wallbang connector door", startingLocation: "lower", nadeType: "wallbang", 
    throwType: "none", side: "CT", description: "", map: "overpass", contentUrl: "https://streamable.com/l/7th7pc/mp4.mp4"},
    { id: "overpass_smoke_stairs_from_long", title: "Smoke stairs", startingLocation: "long", nadeType: "smoke", 
    throwType: "run", side: "T", description: "", map: "overpass", contentUrl: "https://streamable.com/l/bkqedp/mp4.mp4"},
    { id: "overpass_smoke_left_pillar", title: "Smoke left pillar", startingLocation: "below heaven", nadeType: "smoke", 
    throwType: "normal", side: "CT", description: "", map: "overpass", contentUrl: "https://streamable.com/l/904sqz/mp4.mp4"},
    { id: "overpass_smoke_stairs_from_short", title: "Smoke stairs", startingLocation: "divider", nadeType: "smoke", 
    throwType: "normal", side: "T", description: "", map: "overpass", contentUrl: "https://streamable.com/l/z5lmf1/mp4.mp4"},
    { id: "overpass_smoke_heaven_from_site", title: "Smoke heaven", startingLocation: "B site", nadeType: "smoke", 
    throwType: "normal", side: "T", description: "", map: "overpass", contentUrl: "https://streamable.com/l/xkgtb2/mp4.mp4"},
    { id: "overpass_smoke_monster_from_lower", title: "Smoke monster", startingLocation: "lower", nadeType: "smoke", 
    throwType: "normal", side: "CT", description: "", map: "overpass", contentUrl: "https://streamable.com/l/hu7e6c/mp4.mp4"},
    { id: "overpass_smoke_water_from_spawn", title: "Smoke water", startingLocation: "CT spawn", nadeType: "smoke", 
    throwType: "normal", side: "CT", description: "", map: "overpass", contentUrl: "https://streamable.com/l/xg8d1y/mp4.mp4"},
    { id: "overpass_solo_lurk_b", title: "Solo lurk B nades", startingLocation: "canals", nadeType: "molly, flash", 
    throwType: "jump, run", side: "T", description: "", map: "overpass", contentUrl: "https://streamable.com/l/gc34hm/mp4.mp4"},
    { id: "overpass_smoke_heaven_from_water", title: "Smoke heaven", startingLocation: "outside pipe", nadeType: "smoke", 
    throwType: "jump", side: "T", description: "", map: "overpass", contentUrl: "https://streamable.com/l/v8nvr2/mp4.mp4"},
    { id: "overpass_solo_connector_utility_set", title: "Solo connector utility", startingLocation: "connector", nadeType: "molly, flash, he", 
    throwType: "normal, run", side: "T", description: "", map: "overpass", contentUrl: "https://streamable.com/l/mo18xx/mp4.mp4"},
    { id: "overpass_smoke_long_lurk", title: "Long lurk smoke", startingLocation: "long", nadeType: "smoke", 
    throwType: "normal", side: "T", description: "", map: "overpass", contentUrl: "https://streamable.com/l/4vzd2c/mp4.mp4"},
    { id: "overpass_smoke_heaven_from_t_spawn", title: "Smoke heaven", startingLocation: "T spawn", nadeType: "smoke", 
    throwType: "run+jump", side: "T", description: "", map: "overpass", contentUrl: "https://streamable.com/l/bw75a7/mp4.mp4"},
    { id: "overpass_smoke_mid", title: "Smoke mid", startingLocation: "bathrooms", nadeType: "smoke", 
    throwType: "run", side: "CT", description: "", map: "overpass", contentUrl: "https://streamable.com/l/09j81w/mp4.mp4"},
    { id: "overpass_smoke_monster_from_ct_spawn", title: "Smoke monster", startingLocation: "CT spawn", nadeType: "smoke", 
    throwType: "jump", side: "CT", description: "", map: "overpass", contentUrl: "https://streamable.com/l/1vq52f/mp4.mp4"},
    { id: "overpass_smoke_monster_from_truck", title: "Smoke monster", startingLocation: "truck", nadeType: "smoke", 
    throwType: "normal", side: "CT", description: "", map: "overpass", contentUrl: "https://streamable.com/l/9yywhh/mp4.mp4"},
    { id: "overpass_smoke_heaven_from_short_pipe", title: "Smoke heaven", startingLocation: "outside pipe", nadeType: "smoke", 
    throwType: "walk", side: "T", description: "", map: "overpass", contentUrl: "https://streamable.com/l/ufkd52/mp4.mp4"},
    { id: "overpass_smoke_bathrooms_from_party", title: "Smoke bathrooms", startingLocation: "playground", nadeType: "smoke", 
    throwType: "normal", side: "T", description: "", map: "overpass", contentUrl: "https://streamable.com/l/0s64s5/mp4.mp4"},
    { id: "overpass_smoke_bridge", title: "Smoke bridge", startingLocation: "water", nadeType: "smoke", 
    throwType: "normal", side: "T", description: "", map: "overpass", contentUrl: "https://streamable.com/l/884max/mp4.mp4"},
    { id: "overpass_smoke_bathrooms_from_t_spawn", title: "Smoke bathrooms", startingLocation: "T spawn", nadeType: "smoke", 
    throwType: "jump", side: "T", description: "", map: "overpass", contentUrl: "https://streamable.com/l/p5ocwc/mp4.mp4"},
    { id: "overpass_smoke_bathrooms_from_playground", title: "Smoke bathrooms", startingLocation: "playground", nadeType: "smoke", 
    throwType: "normal", side: "T", description: "", map: "overpass", contentUrl: "https://streamable.com/l/pxspp2/mp4.mp4"},
    { id: "overpass_smoke_heaven_from_connector", title: "Smoke heaven", startingLocation: "connector", nadeType: "smoke", 
    throwType: "normal", side: "T", description: "", map: "overpass", contentUrl: "https://streamable.com/l/cml9bq/mp4.mp4"},
    { id: "overpass_smoke_easy_long_lurk", title: "Easy long lurk smoke", startingLocation: "long", nadeType: "smoke", 
    throwType: "jump", side: "T", description: "", map: "overpass", contentUrl: "https://streamable.com/l/joorkl/mp4.mp4"},
    { id: "overpass_smoke_bathroom_from_outside_party", title: "Smoke bathrooms", startingLocation: "outside party", nadeType: "smoke", 
    throwType: "run", side: "T", description: "", map: "overpass", contentUrl: "https://streamable.com/l/s9fskw/mp4.mp4"},
    { id: "overpass_smoke_bridge_from_water", title: "Smoke bridge", startingLocation: "water", nadeType: "smoke", 
    throwType: "normal", side: "T", description: "", map: "overpass", contentUrl: "https://streamable.com/l/sy5mtp/mp4.mp4"},
    { id: "overpass_smoke_bank_from_long", title: "Smoke bank", startingLocation: "long", nadeType: "smoke", 
    throwType: "normal", side: "T", description: "", map: "overpass", contentUrl: "https://streamable.com/l/8pjhbf/mp4.mp4"},
    { id: "overpass_smoke_divider_from_t_spawn", title: "Smoke divier", startingLocation: "T spawn", nadeType: "smoke", 
    throwType: "jump", side: "T", description: "", map: "overpass", contentUrl: "https://streamable.com/l/iximn6/mp4.mp4"},
    { id: "overpass_smoke_heaven", title: "Smoke heaven", startingLocation: "water", nadeType: "smoke", 
    throwType: "normal", side: "T", description: "", map: "overpass", contentUrl: "https://streamable.com/l/32afbx/mp4.mp4"},
    { id: "overpass_popflash_retake_from_monster", title: "A retake flash", startingLocation: "outside monster?", nadeType: "flash", //change this
    throwType: "jump", side: "CT", description: "", map: "overpass", contentUrl: "https://streamable.com/l/ji3ln0/mp4.mp4"},
    { id: "overpass_popflash_long_1", title: "Popflash long 1", startingLocation: "long?", nadeType: "flash", //change
    throwType: "normal", side: "CT", description: "", map: "overpass", contentUrl: "https://streamable.com/l/p5vvv8/mp4.mp4"},
    { id: "overpass_popflash_water_solo_start_of_round", title: "Popflash water (solo)", startingLocation: "water", nadeType: "flash", 
    throwType: "run", side: "CT", description: "", map: "overpass", contentUrl: "https://streamable.com/l/ae4hsy/mp4.mp4"},
    { id: "overpass_popflash_long_2", title: "Popflash long 2", startingLocation: "long?", nadeType: "flash", //change
    throwType: "normal", side: "CT", description: "", map: "overpass", contentUrl: "https://streamable.com/l/gqg7y8/mp4.mp4"},
    { id: "overpass_popflash_monster_from_back_site", title: "Popflash monster", startingLocation: "back B site", nadeType: "flash", 
    throwType: "normal", side: "CT", description: "", map: "overpass", contentUrl: "https://streamable.com/l/n1pinx/mp4.mp4"},
    { id: "overpass_popflash_through_pipe_smoke", title: "Popflash through smoke", startingLocation: "water", nadeType: "flash", 
    throwType: "right click", side: "T", description: "", map: "overpass", contentUrl: "https://streamable.com/l/xshums/mp4.mp4"},
    { id: "overpass_popflash_pipe", title: "Popflash pipe", startingLocation: "B short", nadeType: "flash", 
    throwType: "run, right click", side: "T", description: "", map: "overpass", contentUrl: "https://streamable.com/l/e9eqgd/mp4.mp4"},
    { id: "overpass_popflash_front_bathrooms_from_truck", title: "Popflash front bathrooms", startingLocation: "truck", nadeType: "flash", 
    throwType: "normal", side: "CT", description: "", map: "overpass", contentUrl: "https://streamable.com/l/2tb2cc/mp4.mp4"},
    { id: "overpass_nade_monster_ct", title: "Nade monster", startingLocation: "lower", nadeType: "he", 
    throwType: "normal", side: "CT", description: "", map: "overpass", contentUrl: "https://streamable.com/l/mmxco7/mp4.mp4"},
    { id: "overpass_nade_playground_from_bathrooms", title: "Nade playground", startingLocation: "bathrooms", nadeType: "he", 
    throwType: "run+jump", side: "CT", description: "", map: "overpass", contentUrl: "https://streamable.com/l/f43w0w/mp4.mp4"},
    { id: "overpass_nade_door", title: "Nade connector door", startingLocation: "lower", nadeType: "he", 
    throwType: "normal", side: "CT", description: "", map: "overpass", contentUrl: "https://streamable.com/l/o6674s/mp4.mp4"},
    { id: "overpass_nade_connector_door_easy", title: "Nade connector door (easy)", startingLocation: "lower", nadeType: "he", 
    throwType: "normal", side: "CT", description: "", map: "overpass", contentUrl: "https://streamable.com/l/nbgboj/mp4.mp4"},
    { id: "overpass_molly_headshot", title: "Molly headshot", startingLocation: "water", nadeType: "molly", 
    throwType: "normal", side: "T", description: "", map: "overpass", contentUrl: "https://streamable.com/l/2fpukn/mp4.mp4"},
    { id: "overpass_molly_short_control", title: "Molly short", startingLocation: "control room", nadeType: "molly", 
    throwType: "normal", side: "CT", description: "", map: "overpass", contentUrl: "https://streamable.com/l/lhvnwx/mp4.mp4"},
    { id: "overpass_molly_dumpster_from_top_connector", title: "Molly dumpster", startingLocation: "top connector", nadeType: "molly", 
    throwType: "run+jump", side: "T", description: "", map: "overpass", contentUrl: "https://streamable.com/l/0u9k51/mp4.mp4"},
    { id: "overpass_molly_toxic_from_back_water", title: "Molly toxic", startingLocation: "back water", nadeType: "molly", 
    throwType: "quick run", side: "T", description: "", map: "overpass", contentUrl: "https://streamable.com/l/4e52cf/mp4.mp4"},
    { id: "overpass_molly_lower_from_monster", title: "Molly lower", startingLocation: "monster", nadeType: "molly", 
    throwType: "run", side: "T", description: "", map: "overpass", contentUrl: "https://streamable.com/l/n05el5/mp4.mp4"},
    { id: "overpass_molly_party_from_back_playground", title: "Molly party", startingLocation: "back playground", nadeType: "molly", 
    throwType: "jump", side: "T", description: "", map: "overpass", contentUrl: "https://streamable.com/l/j2cm3d/mp4.mp4"},
    { id: "overpass_molly_short_quick", title: "Molly short (quick)", startingLocation: "T spawn", nadeType: "molly", 
    throwType: "run", side: "T", description: "", map: "overpass", contentUrl: "https://streamable.com/l/cfdzzg/mp4.mp4"},
    { id: "overpass_molly_truck_from_long", title: "Molly truck", startingLocation: "long", nadeType: "molly", 
    throwType: "run", side: "T", description: "", map: "overpass", contentUrl: "https://streamable.com/l/dk4hvb/mp4.mp4"},
    { id: "overpass_molly_truck_from_short", title: "Molly truck", startingLocation: "A short", nadeType: "molly", 
    throwType: "jump", side: "T", description: "", map: "overpass", contentUrl: "https://streamable.com/l/8z2jah/mp4.mp4"},
    { id: "overpass_molly_barrels_from_water", title: "Molly toxic", startingLocation: "water", nadeType: "molly", 
    throwType: "jump", side: "T", description: "", map: "overpass", contentUrl: "https://streamable.com/l/knz0et/mp4.mp4"},
    { id: "overpass_molly_deep_playground", title: "Molly deep playground", startingLocation: "divider", nadeType: "molly", 
    throwType: "run+jump", side: "CT", description: "", map: "overpass", contentUrl: "https://streamable.com/l/cip7i4/mp4.mp4"},
    { id: "overpass_lurk_b_smoke", title: "B lurk smoke", startingLocation: "T spawn", nadeType: "smoke", 
    throwType: "normal", side: "T", description: "", map: "overpass", contentUrl: "https://streamable.com/l/ho8acs/mp4.mp4"},
    { id: "overpass_molly_divider", title: "Molly divider", startingLocation: "fountain", nadeType: "molly", 
    throwType: "quick run", side: "T", description: "", map: "overpass", contentUrl: "https://streamable.com/l/9rj6vz/mp4.mp4"},
    { id: "overpass_molly_default_a_from_long", title: "Molly dice", startingLocation: "long", nadeType: "molly", 
    throwType: "normal", side: "T", description: "", map: "overpass", contentUrl: "https://streamable.com/l/d4nas3/mp4.mp4"},
    { id: "overpass_molly_default_a", title: "Molly dice", startingLocation: "divider", nadeType: "molly", 
    throwType: "jump", side: "T", description: "", map: "overpass", contentUrl: "https://streamable.com/l/jub28n/mp4.mp4"},
    { id: "overpass_molly_deep_connector_from_party", title: "Molly deep connector", startingLocation: "party", nadeType: "molly", 
    throwType: "normal", side: "T", description: "", map: "overpass", contentUrl: "https://streamable.com/l/6h1bvb/mp4.mp4"},
    { id: "overpass_molly_deep_mid", title: "Molly deep mid", startingLocation: "A short", nadeType: "molly", 
    throwType: "run+jump", side: "CT", description: "", map: "overpass", contentUrl: "https://streamable.com/l/qwxn8u/mp4.mp4"},
    { id: "overpass_flash_mid_from_top_long", title: "Flash mid", startingLocation: "top long", nadeType: "flash", 
    throwType: "normal", side: "T", description: "", map: "overpass", contentUrl: "https://streamable.com/l/pwaoj9/mp4.mp4"},
    { id: "overpass_flash_long_bathrooms", title: "Flash long bathrooms", startingLocation: "long", nadeType: "flash", 
    throwType: "run", side: "T", description: "", map: "overpass", contentUrl: "https://streamable.com/l/db1wq7/mp4.mp4"},
    { id: "overpass_flash_support_short", title: "Support flash short", startingLocation: "below heaven", nadeType: "flash",
    throwType: "run", side: "CT", description: "", map: "overpass", contentUrl: "https://streamable.com/l/teyfzp/mp4.mp4"},
    { id: "overpass_flash_short_for_rush", title: "Flash short for B rush", startingLocation: "canals", nadeType: "flash",
    throwType: "normal", side: "T", description: "", map: "overpass", contentUrl: "https://streamable.com/l/yy1222/mp4.mp4"},
    { id: "overpass_flash_party_from_ramp", title: "Flash party", startingLocation: "ramp", nadeType: "flash",
    throwType: "quick run", side: "T", description: "", map: "overpass", contentUrl: "https://streamable.com/l/wbp1zb/mp4.mp4"},
    { id: "overpass_flash_short_from_connector", title: "Flash short", startingLocation: "connector", nadeType: "flash",
    throwType: "quick run", side: "T", description: "", map: "overpass", contentUrl: "https://streamable.com/l/dqp91i/mp4.mp4"},
    { id: "overpass_flashes_for_b_execute", title: "Flashes for B execute", startingLocation: "water", nadeType: "flash",
    throwType: "normal", side: "T", description: "", map: "overpass", contentUrl: "https://streamable.com/l/jukbry/mp4.mp4"},
    { id: "overpass_flash_pop_water", title: "Popflash water", startingLocation: "connector", nadeType: "flash",
    throwType: "normal", side: "T", description: "", map: "overpass", contentUrl: "https://streamable.com/l/ih99mh/mp4.mp4"},
    { id: "overpass_flash_from_playground", title: "Flash above fountain", startingLocation: "playground", nadeType: "flash",
    throwType: "normal", side: "T", description: "", map: "overpass", contentUrl: "https://streamable.com/l/v90uxf/mp4.mp4"},
    { id: "overpass_flash_pop_monster_for_t", title: "Nose flash", startingLocation: "canals", nadeType: "flash",
    throwType: "normal", side: "T", description: "", map: "overpass", contentUrl: "https://streamable.com/l/csmopa/mp4.mp4"},
    { id: "overpass_flash_mid_from_party", title: "Flash mid", startingLocation: "party", nadeType: "flash",
    throwType: "normal", side: "T", description: "", map: "overpass", contentUrl: "https://streamable.com/l/im84qw/mp4.mp4"},
    { id: "overpass_flash_far_long", title: "Flash long", startingLocation: "playground", nadeType: "flash",
    throwType: "jump", side: "T", description: "", map: "overpass", contentUrl: "https://streamable.com/l/kzq38s/mp4.mp4"},
    { id: "overpass_flash_front_bathroom_from_party", title: "Flash front bathrooms", startingLocation: "party", nadeType: "flash",
    throwType: "normal", side: "T", description: "", map: "overpass", contentUrl: "https://streamable.com/l/co9my0/mp4.mp4"},
    { id: "overpass_flash_combo_for_a", title: "Flash combo for A", startingLocation: "A short", nadeType: "flash",
    throwType: "run", side: "T", description: "", map: "overpass", contentUrl: "https://streamable.com/l/oy0efn/mp4.mp4"},
    { id: "overpass_flash_aggressive_ramp_t", title: "Flash for ramp push", startingLocation: "ramp", nadeType: "flash",
    throwType: "quick run", side: "T", description: "", map: "overpass", contentUrl: "https://streamable.com/l/xr0gis/mp4.mp4"},
    { id: "overpass_flash_close_long", title: "Flash long", startingLocation: "long", nadeType: "flash",
    throwType: "normal", side: "T", description: "", map: "overpass", contentUrl: "https://streamable.com/l/vijpvl/mp4.mp4"},
    { id: "overpass_fast_molly_pipe", title: "Molly pipe (fast)", startingLocation: "lower", nadeType: "molly",
    throwType: "run+medium throw", side: "CT", description: "", map: "overpass", contentUrl: "https://streamable.com/l/6r3mp4/mp4.mp4"},
    { id: "overpass_defensive_long_setup", title: "Defense long smoke", startingLocation: "A site", nadeType: "smoke",
    throwType: "quick run", side: "CT", description: "", map: "overpass", contentUrl: "https://streamable.com/l/5knvxy/mp4.mp4"},
    { id: "overpass_defensive_smoke_from_long", title: "Defensive A smoke", startingLocation: "long", nadeType: "smoke",
    throwType: "right click", side: "CT", description: "", map: "overpass", contentUrl: "https://streamable.com/l/43gt0d/mp4.mp4"},
    { id: "overpass_ct_utility_combo_divider", title: "Divider utility", startingLocation: "outside bathrooms", nadeType: "smoke, he",
    throwType: "quick run", side: "CT", description: "", map: "overpass", contentUrl: "https://streamable.com/l/sucwo2/mp4.mp4"},
    { id: "overpass_back_corner_wallbang", title: "Pipe wallbang", startingLocation: "lower", nadeType: "wallbang",
    throwType: "none", side: "CT", description: "", map: "overpass", contentUrl: "https://streamable.com/l/153sm7/mp4.mp4"},
    { id: "overpass_boost_connector_for_pipe", title: "Boost for pipe", startingLocation: "connector", nadeType: "boost",
    throwType: "none", side: "all", description: "", map: "overpass", contentUrl: "https://streamable.com/l/yfh1n8/mp4.mp4"},

    // *********************************************** NUKE ***********************************************

    { id: "nuke_a_exec_back_silo_molly_and_flashes", title: "Back silo molly and flashes", startingLocation: "T roof", nadeType: "molly, flash",
    throwType: "jump", side: "T", description: "", map: "nuke", contentUrl: "https://streamable.com/l/bsby8g/mp4.mp4"},
    { id: "nuke_molly_top_hut_and_flashes", title: "Molly top hut and flashes", startingLocation: "T roof", nadeType: "molly, flash",
    throwType: "run+jump", side: "T", description: "The windows need to be shot out first.", map: "nuke", contentUrl: "https://streamable.com/l/yc34rg/mp4.mp4"},
    { id: "nuke_smoke_hell_from_outside", title: "Smoke hell", startingLocation: "outside", nadeType: "smoke",
    throwType: "run+jump", side: "T", description: "", map: "nuke", contentUrl: "https://streamable.com/l/be7nxc/mp4.mp4"},
    { id: "nuke_smoke_mini_from_silo", title: "Smoke mini", startingLocation: "silo", nadeType: "smoke",
    throwType: "run", side: "T", description: "", map: "nuke", contentUrl: "https://streamable.com/l/grplil/mp4.mp4"},
    { id: "nuke_molly_top_hut_and_flash", title: "Molly top hut and flash", startingLocation: "T roof", nadeType: "molly, flash",
    throwType: "jump", side: "T", description: "", map: "nuke", contentUrl: "https://streamable.com/l/o91oeu/mp4.mp4"},
    { id: "nuke_vent_rush_utility", title: "Vent rush utility", startingLocation: "lobby", nadeType: "smoke, he",
    throwType: "run, right click", side: "T", description: "", map: "nuke", contentUrl: "https://streamable.com/l/51w35n/mp4.mp4"},
    { id: "nuke_vent_smoke", title: "Vent smoke and HE", startingLocation: "lobby", nadeType: "smoke, he",
    throwType: "run", side: "T", description: "", map: "nuke", contentUrl: "https://streamable.com/l/xdilpi/mp4.mp4"},
    { id: "nuke_vent_rush_smoke_from_spawn", title: "Vent rush smoke", startingLocation: "T spawn", nadeType: "smoke",
    throwType: "jump", side: "T", description: "", map: "nuke", contentUrl: "https://streamable.com/l/3r58sp/mp4.mp4"},
    { id: "nuke_smokewall_from_outside2", title: "Smokewall 2", startingLocation: "outside", nadeType: "smoke",
    throwType: "normal", side: "T", description: "", map: "nuke", contentUrl: "https://streamable.com/l/a7anr0/mp4.mp4"},
    { id: "nuke_smokewall_from_spawn2", title: "Smokewall 2", startingLocation: "outside", nadeType: "smoke",
    throwType: "jump", side: "T", description: "", map: "nuke", contentUrl: "https://streamable.com/l/podzn6/mp4.mp4"},
    { id: "nuke_smokewall_from_spawn1", title: "Smokewall 1", startingLocation: "T spawn", nadeType: "smoke",
    throwType: "jump", side: "T", description: "", map: "nuke", contentUrl: "https://streamable.com/l/oyn39o/mp4.mp4"},
    { id: "nuke_smoke_outside_to_peek_silo", title: "Smoke outside (gla1ve smoke)", startingLocation: "CT spawn", nadeType: "smoke",
    throwType: "run", side: "CT", description: "", map: "nuke", contentUrl: "https://streamable.com/l/bo4ejx/mp4.mp4"},
    { id: "nuke_smoke_a_main_from_outside_closer", title: "Smoke A main", startingLocation: "outside A main", nadeType: "smoke",
    throwType: "run", side: "T", description: "", map: "nuke", contentUrl: "https://streamable.com/l/rg34yc/mp4.mp4"},
    { id: "nuke_smoke_squeaky_from_heaven", title: "Smoke squeaky", startingLocation: "heaven", nadeType: "smoke",
    throwType: "normal", side: "CT", description: "", map: "nuke", contentUrl: "https://streamable.com/l/t7jkuj/mp4.mp4"},
    { id: "nuke_smokewall_from_outside1", title: "Smokewall 1", startingLocation: "outside", nadeType: "smoke",
    throwType: "normal", side: "T", description: "", map: "nuke", contentUrl: "https://streamable.com/l/6zz7z9/mp4.mp4"},
    { id: "nuke_smoke_garage", title: "Smoke garage", startingLocation: "outside", nadeType: "smoke",
    throwType: "normal", side: "T", description: "", map: "nuke", contentUrl: "https://streamable.com/l/lrftb5/mp4.mp4"},
    { id: "nuke_smoke_default", title: "Smoke default", startingLocation: "vending", nadeType: "smoke",
    throwType: "walk", side: "T", description: "", map: "nuke", contentUrl: "https://streamable.com/l/a71jmu/mp4.mp4"},
    { id: "nuke_smoke_a_main_from_outside", title: "Smoke A main", startingLocation: "outside", nadeType: "smoke",
    throwType: "run", side: "T", description: "", map: "nuke", contentUrl: "https://streamable.com/l/wih1a2/mp4.mp4"},
    { id: "nuke_smoke_a_main", title: "Smoke A main (and HE)", startingLocation: "lobby", nadeType: "smoke, he",
    throwType: "run", side: "T", description: "", map: "nuke", contentUrl: "https://streamable.com/l/361awx/mp4.mp4"},
    { id: "nuke_ramp_lamp_flash", title: "Lamp flash", startingLocation: "ramp", nadeType: "flash",
    throwType: "normal", side: "T", description: "", map: "nuke", contentUrl: "https://streamable.com/l/w8p5ir/mp4.mp4"},
    { id: "nuke_pop_flash_vent", title: "Popflash vent", startingLocation: "A site", nadeType: "flash",
    throwType: "right click", side: "all", description: "", map: "nuke", contentUrl: "https://streamable.com/l/jh1nlq/mp4.mp4"},
    { id: "nuke_ramp_anti_rush_utility", title: "Anti-rush utility", startingLocation: "ramp", nadeType: "smoke, he",
    throwType: "run", side: "CT", description: "", map: "nuke", contentUrl: "https://streamable.com/l/jacijo/mp4.mp4"},
    { id: "nuke_ramp_utility_set_t_side", title: "T side ramp utility", startingLocation: "ramp", nadeType: "smoke, flash",
    throwType: "normal, run", side: "T", description: "", map: "nuke", contentUrl: "https://streamable.com/l/cf437x/mp4.mp4"},
    { id: "nuke_molly_dark", title: "Molly dark", startingLocation: "below ramp", nadeType: "molly",
    throwType: "normal", side: "all", description: "", map: "nuke", contentUrl: "https://streamable.com/l/fcyeu2/mp4.mp4"},
    { id: "nuke_molly_for_ct_hut_rush", title: "Fake hut molly", startingLocation: "heaven", nadeType: "molly",
    throwType: "normal", side: "CT", description: "", map: "nuke", contentUrl: "https://streamable.com/l/qfw07l/mp4.mp4"},
    { id: "nuke_molly_double_doors", title: "Molly double doors", startingLocation: "below ramp", nadeType: "molly",
    throwType: "quick run", side: "T", description: "", map: "nuke", contentUrl: "https://streamable.com/l/4kls5n/mp4.mp4"},
    { id: "nuke_molly_behind_blue_box_two_ways", title: "Molly behind blue box", startingLocation: "top mini", nadeType: "molly",
    throwType: "run", side: "T", description: "", map: "nuke", contentUrl: "https://streamable.com/l/f4ei5v/mp4.mp4"},
    { id: "nuke_molly_secret_from_outside", title: "Molly secret", startingLocation: "outside", nadeType: "molly",
    throwType: "normal", side: "T", description: "", map: "nuke", contentUrl: "https://streamable.com/l/rutfhq/mp4.mp4"},
    { id: "nuke_mini_smoke_utility_combo_from_top_mini", title: "Top mini utility", startingLocation: "top mini", nadeType: "smoke, molly, flash",
    throwType: "normal, run", side: "T", description: "", map: "nuke", contentUrl: "https://streamable.com/l/7qm2bt/mp4.mp4"},
    { id: "nuke_molly_squeaky_from_heaven", title: "Molly squeaky", startingLocation: "heaven", nadeType: "molly",
    throwType: "run", side: "CT", description: "", map: "nuke", contentUrl: "https://streamable.com/l/tkkzmi/mp4.mp4"},
    { id: "nuke_molly_outside_prevent_rush", title: "Molly outside anti-rush", startingLocation: "CT spawn", nadeType: "molly",
    throwType: "walk+jump", side: "CT", description: "", map: "nuke", contentUrl: "https://streamable.com/l/f9cw0i/mp4.mp4"},
    { id: "nuke_molly_silo", title: "Molly silo", startingLocation: "blue box", nadeType: "molly",
    throwType: "jump", side: "CT", description: "", map: "nuke", contentUrl: "https://streamable.com/l/k9lge2/mp4.mp4"},
    { id: "nuke_flash_to_cross_to_secret", title: "Flash to cross secret", startingLocation: "outside", nadeType: "flash",
    throwType: "run", side: "CT", description: "", map: "nuke", contentUrl: "https://streamable.com/l/absc96/mp4.mp4"},
    { id: "nuke_flash_outside_start_of_round", title: "Flash outside", startingLocation: "CT spawn", nadeType: "flash",
    throwType: "run", side: "CT", description: "", map: "nuke", contentUrl: "https://streamable.com/l/2pxt96/mp4.mp4"},
    { id: "nuke_defensive_ramp_molly", title: "Defensive ramp molly", startingLocation: "ramp", nadeType: "molly",
    throwType: "normal", side: "CT", description: "", map: "nuke", contentUrl: "https://streamable.com/l/jz3hs3/mp4.mp4"},
    { id: "nuke_deep_smokewall_pair", title: "Deep smokewall pair", startingLocation: "outside", nadeType: "smoke",
    throwType: "jump", side: "T", description: "", map: "nuke", contentUrl: "https://streamable.com/l/u43ov9/mp4.mp4"},
    { id: "nuke_cheeky_ramp_smoke", title: "Ramp smoke using gap", startingLocation: "ramp", nadeType: "smoke",
    throwType: "normal", side: "CT", description: "", map: "nuke", contentUrl: "https://streamable.com/l/k739n5/mp4.mp4"},
    { id: "nuke_aleksib_cross_smoke", title: "Cross smoke", startingLocation: "T spawn", nadeType: "smoke",
    throwType: "run", side: "T", description: "", map: "nuke", contentUrl: "https://streamable.com/l/6ytgay/mp4.mp4"},
    { id: "nuke_a_exec_molly_fake_vent", title: "Molly fake vent", startingLocation: "lobby", nadeType: "molly",
    throwType: "quick run", side: "T", description: "", map: "nuke", contentUrl: "https://streamable.com/l/6myq1k/mp4.mp4"},
    { id: "nuke_a_exec_heaven_smoke_mustang_molly", title: "Heaven smoke + mustang molly", startingLocation: "silo", nadeType: "smoke, molly",
    throwType: "normal", side: "T", description: "", map: "nuke", contentUrl: "https://streamable.com/l/1h9sl3/mp4.mp4"},
    { id: "nuke_a_exec_back_silo_molly_and_flashes", title: "Back silo molly and flashes", startingLocation: "T roof", nadeType: "flash, molly",
    throwType: "jump", side: "T", description: "", map: "nuke", contentUrl: "https://streamable.com/l/1o6rhn/mp4.mp4"},

  // *********************************************** MIRAGE ***********************************************

    { id: "mirage_easy_smoke_cross_from_top_mid", title: "Cross smoke", startingLocation: "top mid", nadeType: "smoke",
    throwType: "normal", side: "T", description: "", map: "mirage", contentUrl: "https://streamable.com/l/ai6y3u/mp4.mp4"},
    { id: "mirage_b_retake_smoke_from_market", title: "B retake smoke", startingLocation: "market", nadeType: "smoke",
    throwType: "normal", side: "all", description: "", map: "mirage", contentUrl: "https://streamable.com/l/3ldmfe/mp4.mp4"},
    { id: "mirage_t_ramp_lurk_smoke", title: "T ramp lurk smoke", startingLocation: "ramp", nadeType: "smoke",
    throwType: "normal", side: "T", description: "", map: "mirage", contentUrl: "https://streamable.com/l/k32da0/mp4.mp4"},
    { id: "mirage_smoke_top_connector_from_mid", title: "Top connector smoke", startingLocation: "mid", nadeType: "smoke",
    throwType: "quick run", side: "T", description: "", map: "mirage", contentUrl: "https://streamable.com/l/aooatj/mp4.mp4"},
    { id: "mirage_smoke_top_connector_from_top_mid", title: "Smoke top connector", startingLocation: "top mid", nadeType: "smoke",
    throwType: "jump", side: "T", description: "", map: "mirage", contentUrl: "https://streamable.com/l/zd0d41/mp4.mp4"},
    { id: "mirage_smoke_top_connector_from_spawn", title: "Smoke top connector", startingLocation: "T spawn", nadeType: "smoke",
    throwType: "crouch+jump", side: "T", description: "", map: "mirage", contentUrl: "https://streamable.com/l/ykwbo7/mp4.mp4"},
    { id: "mirage_smoke_left_side_arch", title: "Smoke left side arch", startingLocation: "outside back apts", nadeType: "smoke",
    throwType: "jump", side: "T", description: "", map: "mirage", contentUrl: "https://streamable.com/l/qdpqe0/mp4.mp4"},
    { id: "mirage_smoke_catwalk_rail", title: "Smoke catwalk rail", startingLocation: "T spawn", nadeType: "smoke",
    throwType: "jump", side: "T", description: "", map: "mirage", contentUrl: "https://streamable.com/l/97a4zm/mp4.mp4"},
    { id: "mirage_smoke_mid_window_from_top_mid_quick", title: "Smoke window (quick)", startingLocation: "top mid", nadeType: "smoke",
    throwType: "run", side: "T", description: "", map: "mirage", contentUrl: "https://streamable.com/l/p9wlwj/mp4.mp4"},
    { id: "mirage_smoke_mid_window", title: "Smoke window (lineup)", startingLocation: "top mid", nadeType: "smoke",
    throwType: "normal", side: "T", description: "", map: "mirage", contentUrl: "https://streamable.com/l/eluhea/mp4.mp4"},
    { id: "mirage_smoke_mid_window_from_spawn_alternate", title: "Smoke window from spawn (alternate)", startingLocation: "T spawn", nadeType: "smoke",
    throwType: "jump throw", side: "T", description: "", map: "mirage", contentUrl: "https://streamable.com/l/nxcj9t/mp4.mp4"}, //this should probably have a new throw category
    { id: "mirage_smoke_market_window", title: "Smoke market window", startingLocation: "apartments", nadeType: "smoke",
    throwType: "jump", side: "T", description: "", map: "mirage", contentUrl: "https://streamable.com/l/3qee3m/mp4.mp4"},
    { id: "mirage_smoke_market_door", title: "Smoke market door", startingLocation: "apartments", nadeType: "smoke",
    throwType: "jump", side: "T", description: "", map: "mirage", contentUrl: "https://streamable.com/l/fqk0dl/mp4.mp4"},
    { id: "mirage_smoke_palace_from_outside_market", title: "Smoke palace", startingLocation: "outside market", nadeType: "smoke",
    throwType: "jump", side: "CT", description: "", map: "mirage", contentUrl: "https://streamable.com/l/9n6b0g/mp4.mp4"},
    { id: "mirage_smoke_stairs", title: "Smoke stairs", startingLocation: "ramp", nadeType: "smoke",
    throwType: "normal", side: "T", description: "", map: "mirage", contentUrl: "https://streamable.com/l/owfmgy/mp4.mp4"},
    { id: "mirage_smoke_right_side_arch", title: "Smoke right side arch", startingLocation: "outside back apts", nadeType: "smoke",
    throwType: "jump", side: "T", description: "", map: "mirage", contentUrl: "https://streamable.com/l/k60j4n/mp4.mp4"},
    { id: "mirage_smoke_safe_a_ramp", title: "Safe A ramp smoke", startingLocation: "ticket", nadeType: "smoke",
    throwType: "normal", side: "CT", description: "", map: "mirage", contentUrl: "https://streamable.com/l/80rvjf/mp4.mp4"},
    { id: "mirage_smoke_mid_window_alternate", title: "Smoke window", startingLocation: "T spawn", nadeType: "smoke", //which is actually alternate???
    throwType: "run+jump", side: "T", description: "", map: "mirage", contentUrl: "https://streamable.com/l/1r67xf/mp4.mp4"},
    { id: "mirage_smoke_jungle_from_site", title: "Smoke jungle", startingLocation: "A site", nadeType: "smoke",
    throwType: "normal", side: "T", description: "", map: "mirage", contentUrl: "https://streamable.com/l/kvcnws/mp4.mp4"},
    { id: "mirage_smoke_jungle", title: "Smoke jungle", startingLocation: "ramp", nadeType: "smoke",
    throwType: "normal", side: "T", description: "", map: "mirage", contentUrl: "https://streamable.com/l/awtf6f/mp4.mp4"},
    { id: "mirage_smoke_top_mid", title: "Smoke top mid", startingLocation: "T spawn", nadeType: "smoke",
    throwType: "normal", side: "T", description: "", map: "mirage", contentUrl: "https://streamable.com/l/y0qnzp/mp4.mp4"}, //might wanna get rid of this
    { id: "mirage_smoke_go_catwalk", title: "Run up catwalk smoke", startingLocation: "catwalk", nadeType: "smoke",
    throwType: "right click", side: "T", description: "", map: "mirage", contentUrl: "https://streamable.com/l/h9mgpu/mp4.mp4"},
    { id: "mirage_smoke_ct_from_site", title: "Smoke CT", startingLocation: "A site", nadeType: "smoke",
    throwType: "normal", side: "T", description: "", map: "mirage", contentUrl: "https://streamable.com/l/sln3kn/mp4.mp4"},
    { id: "mirage_smoke_ct_best", title: "Smoke CT", startingLocation: "T spawn", nadeType: "smoke",
    throwType: "jump", side: "T", description: "", map: "mirage", contentUrl: "https://streamable.com/l/yc8o7m/mp4.mp4"},
    { id: "mirage_smoke_ct", title: "Smoke CT", startingLocation: "T spawn", nadeType: "smoke",
    throwType: "jump", side: "T", description: "", map: "mirage", contentUrl: "https://streamable.com/l/un2flw/mp4.mp4"},
    { id: "mirage_smoke_connector_from_palace", title: "Smoke connector", startingLocation: "palace", nadeType: "smoke",
    throwType: "normal", side: "T", description: "", map: "mirage", contentUrl: "https://streamable.com/l/7hrmkw/mp4.mp4"},
    { id: "mirage_smoke_catwalk_from_underpass", title: "Smoke catwalk", startingLocation: "underpass", nadeType: "smoke",
    throwType: "normal", side: "T", description: "", map: "mirage", contentUrl: "https://streamable.com/l/u4ebp0/mp4.mp4"},
    { id: "mirage_smoke_catwalk_from_t_spawn", title: "Smoke catwalk", startingLocation: "T spawn", nadeType: "smoke",
    throwType: "jump", side: "T", description: "", map: "mirage", contentUrl: "https://streamable.com/l/ie9vsm/mp4.mp4"},
    { id: "mirage_smoke_catwalk", title: "Smoke catwalk", startingLocation: "top mid", nadeType: "smoke",
    throwType: "normal", side: "T", description: "", map: "mirage", contentUrl: "https://streamable.com/l/s56sm7/mp4.mp4"},
    { id: "mirage_smoke_connector_from_a_site", title: "Smoke connector", startingLocation: "A site", nadeType: "smoke",
    throwType: "normal", side: "T", description: "", map: "mirage", contentUrl: "https://streamable.com/l/yptqcn/mp4.mp4"},
    { id: "mirage_smoke_bench_deep_apts", title: "Smoke bench", startingLocation: "apartments", nadeType: "smoke",
    throwType: "normal", side: "T", description: "", map: "mirage", contentUrl: "https://streamable.com/l/d028mg/mp4.mp4"},
    { id: "mirage_ramp_retake_utility", title: "Ramp retake utility", startingLocation: "jungle", nadeType: "smoke, molly",
    throwType: "normal", side: "CT", description: "", map: "mirage", contentUrl: "https://streamable.com/l/cgeix1/mp4.mp4"},
    { id: "mirage_smoke_balcony", title: "Smoke balcony", startingLocation: "apartments", nadeType: "smoke",
    throwType: "jump", side: "T", description: "", map: "mirage", contentUrl: "https://streamable.com/l/6dkb06/mp4.mp4"},
    { id: "mirage_retake_utility_from_van_1", title: "Retake utility from van", startingLocation: "van", nadeType: "smoke, molly, he",
    throwType: "normal", side: "all", description: "", map: "mirage", contentUrl: "https://streamable.com/l/5z1tfe/mp4.mp4"},
    { id: "mirage_quick_smoke_ramp", title: "Quick smoke ramp", startingLocation: "CT spawn", nadeType: "smoke",
    throwType: "jump", side: "CT", description: "", map: "mirage", contentUrl: "https://streamable.com/l/aky4pk/mp4.mp4"},
    { id: "mirage_smoke_arches", title: "Smoke arch", startingLocation: "apartments", nadeType: "smoke",
    throwType: "normal", side: "T", description: "", map: "mirage", contentUrl: "https://streamable.com/l/f3gcom/mp4.mp4"},
    { id: "mirage_popflash_stairs", title: "Popflash stairs", startingLocation: "stairs", nadeType: "flash",
    throwType: "run", side: "CT", description: "", map: "mirage", contentUrl: "https://streamable.com/l/bda1n8/mp4.mp4"},
    { id: "mirage_molly_jungle_from_palace", title: "Molly jungle", startingLocation: "palace", nadeType: "molly",
    throwType: "quick run ", side: "T", description: "", map: "mirage", contentUrl: "https://streamable.com/l/6h26ly/mp4.mp4"},
    { id: "mirage_molly_ramp_from_jungle", title: "Molly ramp", startingLocation: "jungle", nadeType: "molly",
    throwType: "normal", side: "CT", description: "", map: "mirage", contentUrl: "https://streamable.com/l/m99o99/mp4.mp4"},
    { id: "mirage_molly_jungle", title: "Molly jungle", startingLocation: "jungle", nadeType: "molly",
    throwType: "run", side: "T", description: "", map: "mirage", contentUrl: "https://streamable.com/l/l6dr8y/mp4.mp4"},
    { id: "mirage_molly_edward_from_cat", title: "Molly Edward", startingLocation: "catwalk", nadeType: "molly",
    throwType: "normal", side: "all", description: "", map: "mirage", contentUrl: "https://streamable.com/l/13572j/mp4.mp4"},
    { id: "mirage_flash_to_peek_mid_for_catwalk", title: "Peek mid flash", startingLocation: "catwalk", nadeType: "flash",
    throwType: "run", side: "CT", description: "", map: "mirage", contentUrl: "https://streamable.com/l/i2odst/mp4.mp4"},
    { id: "mirage_molly_bench_from_apts", title: "Molly bench", startingLocation: "apartments", nadeType: "molly",
    throwType: "run", side: "T", description: "", map: "mirage", contentUrl: "https://streamable.com/l/w5ywa8/mp4.mp4"},
    { id: "mirage_molly_b_site_default_from_apts", title: "Molly B site default", startingLocation: "apartments", nadeType: "molly",
    throwType: "normal", side: "T", description: "", map: "mirage", contentUrl: "https://streamable.com/l/xe2jx2/mp4.mp4"},
    { id: "mirage_flash_retake_ticket_booth", title: "Retake flash", startingLocation: "ticket booth", nadeType: "flash",
    throwType: "normal", side: "CT", description: "", map: "mirage", contentUrl: "https://streamable.com/l/molo4k/mp4.mp4"},
    { id: "mirage_flash_ramp", title: "Flash ramp", startingLocation: "under palace", nadeType: "flash",
    throwType: "jump", side: "CT", description: "", map: "mirage", contentUrl: "https://streamable.com/l/kfuj3w/mp4.mp4"},
    { id: "mirage_flash_pop_palace", title: "Popflash A site", startingLocation: "palace", nadeType: "flash",
    throwType: "quick run", side: "T", description: "", map: "mirage", contentUrl: "https://streamable.com/l/7xi7wq/mp4.mp4"},
    { id: "mirage_conP_smoke_for_mid_aggression", title: "Smoke for mid aggression", startingLocation: "connector", nadeType: "smoke",
    throwType: "run", side: "CT", description: "Peek out of this somke with a flash over mid from a teammate.", map: "mirage", contentUrl: "https://streamable.com/l/552pq0/mp4.mp4"},
    { id: "mirage_flash_market_door_retake", title: "Retake flash for B", startingLocation: "market door", nadeType: "flash",
    throwType: "normal", side: "CT", description: "", map: "mirage", contentUrl: "https://streamable.com/l/qpoeez/mp4.mp4"},
    { id: "mirage_flash_cross_connector", title: "Cross connector flash", startingLocation: "catwalk", nadeType: "flash",
    throwType: "normal", side: "T", description: "", map: "mirage", contentUrl: "https://streamable.com/l/o2p9f2/mp4.mp4"},
    { id: "mirage_flash_cat_from_back_apts", title: "Flash cat", startingLocation: "back apts", nadeType: "flash",
    throwType: "jump", side: "T", description: "", map: "mirage", contentUrl: "https://streamable.com/l/z99owt/mp4.mp4"},
    { id: "mirage_conP_molly_ramp", title: "Molly ramp", startingLocation: "ticket booth", nadeType: "molly",
    throwType: "run", side: "CT", description: "", map: "mirage", contentUrl: "https://streamable.com/l/mrq4vy/mp4.mp4"},
    { id: "mirage_flash_peek_mid", title: "Peek mid flash", startingLocation: "top mid", nadeType: "flash",
    throwType: "normal", side: "T", description: "", map: "mirage", contentUrl: "https://streamable.com/l/3r7yp1/mp4.mp4"},
    { id: "mirage_b_anchor_setup_delayed", title: "B anchor setup", startingLocation: "van", nadeType: "smoke, flash",
    throwType: "run, normal", side: "CT", description: "", map: "mirage", contentUrl: "https://streamable.com/l/vm8el1/mp4.mp4"},
    { id: "mirage_b_anchor_setup_counter_awp_pick", title: "Counter AWP util", startingLocation: "van", nadeType: "molly, he",
    throwType: "quick run, run", side: "CT", description: "", map: "mirage", contentUrl: "https://streamable.com/l/as297x/mp4.mp4"},
    { id: "mirage_molly_dark_from_palace", title: "Molly dark", startingLocation: "palace", nadeType: "molly",
    throwType: "run", side: "T", description: "", map: "mirage", contentUrl: "https://streamable.com/l/ikmi5z/mp4.mp4"},
    { id: "mirage_molly_connector_from_mid", title: "Molly connector from mid", startingLocation: "mid", nadeType: "molly",
    throwType: "run", side: "T", description: "", map: "mirage", contentUrl: "https://streamable.com/l/q7s23j/mp4.mp4"},
    { id: "mirage_smoke_cross", title: "Smoke cross", startingLocation: "T spawn", nadeType: "smoke",
    throwType: "normal", side: "T", description: "", map: "mirage", contentUrl: "https://streamable.com/l/meeh9x/mp4.mp4"},
    { id: "mirage_flash_pop_b", title: "Popflash B site", startingLocation: "inside apts", nadeType: "flash",
    throwType: "run", side: "T", description: "", map: "mirage", contentUrl: "https://streamable.com/l/60rq7l/mp4.mp4"},
    { id: "mirage_smoke_bench", title: "Smoke bench", startingLocation: "inside apts", nadeType: "smoke",
    throwType: "normal", side: "T", description: "", map: "mirage", contentUrl: "https://streamable.com/l/qmkbwl/mp4.mp4"},
    { id: "mirage_smoke_b_apts", title: "Smoke B apts", startingLocation: "trash can", nadeType: "smoke",
    throwType: "normal", side: "CT", description: "", map: "mirage", contentUrl: "https://streamable.com/l/rv3bll/mp4.mp4"},
    { id: "mirage_catP_smoke_mid_catwalk_for_ct", title: "Mid catwalk smoke", startingLocation: "catwalk", nadeType: "smoke",
    throwType: "normal", side: "CT", description: "", map: "mirage", contentUrl: "https://streamable.com/l/rz4ugs/mp4.mp4"},
    { id: "mirage_catwalk_utility_set_ct", title: "Catwalk CT utility", startingLocation: "catwalk", nadeType: "smoke, molly, flash",
    throwType: "normal, quick run", side: "CT", description: "", map: "mirage", contentUrl: "https://streamable.com/l/kx2t47/mp4.mp4"},
    { id: "mirage_conP_molly_palace", title: "Molly palace", startingLocation: "connector", nadeType: "molly",
    throwType: "normal", side: "CT", description: "", map: "mirage", contentUrl: "https://streamable.com/l/fbeydz/mp4.mp4"},
    { id: "mirage_bench_boost_setup", title: "Bench boost", startingLocation: "B bench", nadeType: "boost",
    throwType: "none", side: "CT", description: "", map: "mirage", contentUrl: "https://streamable.com/l/nuf2vm/mp4.mp4"},
    { id: "mirage_b_afterplant_utility", title: "B afterplant utility", startingLocation: "B site", nadeType: "molly, smoke, flash",
    throwType: "jump", side: "T", description: "", map: "mirage", contentUrl: "https://streamable.com/l/qxgyxf/mp4.mp4"},
    { id: "mirage_b_retake_flashes_from_back_market", title: "B retake flashes", startingLocation: "outside market", nadeType: "flash",
    throwType: "jump", side: "CT", description: "", map: "mirage", contentUrl: "https://streamable.com/l/5em7g5/mp4.mp4"},
    { id: "mirage_utility_set_from_tetris_t", title: "Utility set for T", startingLocation: "tetris", nadeType: "molly, flash, he",
    throwType: "jump, run", side: "T", description: "", map: "mirage", contentUrl: "https://streamable.com/l/zstrju/mp4.mp4"},
    { id: "mirage_aggressive_mid_flash_thru_connector", title: "Mid support flash thru connector", startingLocation: "A site", nadeType: "flash",
    throwType: "normal", side: "CT", description: "", map: "mirage", contentUrl: "https://streamable.com/l/p4slc0/mp4.mp4"},
    { id: "mirage_a_retake_utility_from_ticket", title: "Retake utility", startingLocation: "ticket", nadeType: "molly, flash, he",
    throwType: "jump, normal, run", side: "CT", description: "", map: "mirage", contentUrl: "https://streamable.com/l/9tdny1/mp4.mp4"},
    { id: "mirage_support_flash_ct_for_t", title: "Support flash CT for T", startingLocation: "A site", nadeType: "flash",
    throwType: "normal", side: "T", description: "", map: "mirage", contentUrl: "https://streamable.com/l/bciwkg/mp4.mp4"},

]