import { Grenade } from "./grenade";

// TODO: All the id's in here are being used. Every filename without an ID should be deleted.

export const GRENADES: Grenade[] = [



  // *********************************************** CS:GO OVERPASS ***********************************************

  { id: "overpass_a_execute_combo_from_short", title: "A execute nades", startingLocation: "divider", nadeType: "smoke, molly, flash", 
  throwType: "normal, jump", side: "T", description: "Use this to execute A.", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/w4z08t/mp4.mp4"},
  { id: "overpass_smoke_bank_from_outside_connector", title: "Smoke bank", startingLocation: "outside connector", nadeType: "smoke", 
  throwType: "jump", side: "T", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/3e0k0p/mp4.mp4"},
  { id: "overpass_anti_eco_a_utility", title: "Anti-eco utility for A", startingLocation: "CT spawn", nadeType: "molly, flash", 
  throwType: "normal, jump", side: "CT", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/jskaxw/mp4.mp4"},
  { id: "overpass_molly_toxic_for_real", title: "Molly toxic", startingLocation: "canals", nadeType: "molly", 
  throwType: "forward jump", side: "T", description: "This is a forward+jump throw.", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/177ygl/mp4.mp4"},
  { id: "overpass_support_flash_monster", title: "Support flash monster", startingLocation: "heaven", nadeType: "flash", 
  throwType: "run", side: "CT", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/48i8fc/mp4.mp4"},
  { id: "overpass_support_flash_b_from_a", title: "Support flash B", startingLocation: "CT spawn", nadeType: "flash", 
  throwType: "run", side: "CT", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/m1rer5/mp4.mp4"},
  { id: "overpass_support_flash_over_monster", title: "Support flash over monster", startingLocation: "canals", nadeType: "flash", 
  throwType: "normal", side: "T", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/t6u3i5/mp4.mp4"},
  { id: "overpass_support_flash_mid", title: "Support flash mid", startingLocation: "outside bathrooms", nadeType: "flash", 
  throwType: "normal", side: "CT", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/1nhpgl/mp4.mp4"},
  { id: "overpass_support_flash_deep_monster", title: "Support flash deep monster", startingLocation: "headshot", nadeType: "flash", 
  throwType: "jump", side: "CT", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/fsyd7d/mp4.mp4"},
  { id: "overpass_wallbang_door", title: "Wallbang connector door", startingLocation: "lower", nadeType: "wallbang", 
  throwType: "none", side: "CT", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/7th7pc/mp4.mp4"},
  { id: "overpass_smoke_stairs_from_long", title: "Smoke stairs", startingLocation: "long", nadeType: "smoke", 
  throwType: "run", side: "T", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/bkqedp/mp4.mp4"},
  { id: "overpass_smoke_left_pillar", title: "Smoke left pillar", startingLocation: "below heaven", nadeType: "smoke", 
  throwType: "normal", side: "CT", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/904sqz/mp4.mp4"},
  { id: "overpass_smoke_stairs_from_short", title: "Smoke stairs", startingLocation: "divider", nadeType: "smoke", 
  throwType: "normal", side: "T", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/z5lmf1/mp4.mp4"},
  { id: "overpass_smoke_heaven_from_site", title: "Smoke heaven", startingLocation: "B site", nadeType: "smoke", 
  throwType: "normal", side: "T", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/xkgtb2/mp4.mp4"},
  { id: "overpass_smoke_monster_from_lower", title: "Smoke monster", startingLocation: "lower", nadeType: "smoke", 
  throwType: "normal", side: "CT", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/hu7e6c/mp4.mp4"},
  { id: "overpass_smoke_water_from_spawn", title: "Smoke water", startingLocation: "CT spawn", nadeType: "smoke", 
  throwType: "normal", side: "CT", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/xg8d1y/mp4.mp4"},
  { id: "overpass_solo_lurk_b", title: "Solo lurk B nades", startingLocation: "canals", nadeType: "molly, flash", 
  throwType: "jump, run", side: "T", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/gc34hm/mp4.mp4"},
  { id: "overpass_smoke_heaven_from_water", title: "Smoke heaven", startingLocation: "outside pipe", nadeType: "smoke", 
  throwType: "jump", side: "T", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/v8nvr2/mp4.mp4"},
  { id: "overpass_solo_connector_utility_set", title: "Solo connector utility", startingLocation: "connector", nadeType: "molly, flash, he", 
  throwType: "normal, run", side: "T", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/mo18xx/mp4.mp4"},
  { id: "overpass_smoke_long_lurk", title: "Long lurk smoke", startingLocation: "long", nadeType: "smoke", 
  throwType: "normal", side: "T", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/4vzd2c/mp4.mp4"},
  { id: "overpass_smoke_heaven_from_t_spawn", title: "Smoke heaven", startingLocation: "T spawn", nadeType: "smoke", 
  throwType: "run+jump", side: "T", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/bw75a7/mp4.mp4"},
  { id: "overpass_smoke_mid", title: "Smoke mid", startingLocation: "bathrooms", nadeType: "smoke", 
  throwType: "run", side: "CT", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/09j81w/mp4.mp4"},
  { id: "overpass_smoke_monster_from_ct_spawn", title: "Smoke monster", startingLocation: "CT spawn", nadeType: "smoke", 
  throwType: "jump", side: "CT", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/1vq52f/mp4.mp4"},
  { id: "overpass_smoke_monster_from_truck", title: "Smoke monster", startingLocation: "truck", nadeType: "smoke", 
  throwType: "normal", side: "CT", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/9yywhh/mp4.mp4"},
  { id: "overpass_smoke_heaven_from_short_pipe", title: "Smoke heaven", startingLocation: "outside pipe", nadeType: "smoke", 
  throwType: "walk", side: "T", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/ufkd52/mp4.mp4"},
  { id: "overpass_smoke_bathrooms_from_party", title: "Smoke bathrooms", startingLocation: "playground", nadeType: "smoke", 
  throwType: "normal", side: "T", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/0s64s5/mp4.mp4"},
  { id: "overpass_smoke_bridge", title: "Smoke bridge", startingLocation: "water", nadeType: "smoke", 
  throwType: "normal", side: "T", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/884max/mp4.mp4"},
  { id: "overpass_smoke_bathrooms_from_t_spawn", title: "Smoke bathrooms", startingLocation: "T spawn", nadeType: "smoke", 
  throwType: "jump", side: "T", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/p5ocwc/mp4.mp4"},
  { id: "overpass_smoke_bathrooms_from_playground", title: "Smoke bathrooms", startingLocation: "playground", nadeType: "smoke", 
  throwType: "normal", side: "T", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/pxspp2/mp4.mp4"},
  { id: "overpass_smoke_heaven_from_connector", title: "Smoke heaven", startingLocation: "connector", nadeType: "smoke", 
  throwType: "normal", side: "T", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/cml9bq/mp4.mp4"},
  { id: "overpass_smoke_easy_long_lurk", title: "Easy long lurk smoke", startingLocation: "long", nadeType: "smoke", 
  throwType: "jump", side: "T", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/joorkl/mp4.mp4"},
  { id: "overpass_smoke_bathroom_from_outside_party", title: "Smoke bathrooms", startingLocation: "outside party", nadeType: "smoke", 
  throwType: "run", side: "T", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/s9fskw/mp4.mp4"},
  { id: "overpass_smoke_bridge_from_water", title: "Smoke bridge", startingLocation: "water", nadeType: "smoke", 
  throwType: "normal", side: "T", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/sy5mtp/mp4.mp4"},
  { id: "overpass_smoke_bank_from_long", title: "Smoke bank", startingLocation: "long", nadeType: "smoke", 
  throwType: "normal", side: "T", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/8pjhbf/mp4.mp4"},
  { id: "overpass_smoke_divider_from_t_spawn", title: "Smoke divier", startingLocation: "T spawn", nadeType: "smoke", 
  throwType: "jump", side: "T", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/iximn6/mp4.mp4"},
  { id: "overpass_smoke_heaven", title: "Smoke heaven", startingLocation: "water", nadeType: "smoke", 
  throwType: "normal", side: "T", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/32afbx/mp4.mp4"},
  { id: "overpass_popflash_retake_from_monster", title: "A retake flash", startingLocation: "outside monster?", nadeType: "flash", //change this
  throwType: "jump", side: "CT", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/ji3ln0/mp4.mp4"},
  { id: "overpass_popflash_long_1", title: "Popflash long 1", startingLocation: "long?", nadeType: "flash", //change
  throwType: "normal", side: "CT", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/p5vvv8/mp4.mp4"},
  { id: "overpass_popflash_water_solo_start_of_round", title: "Popflash water (solo)", startingLocation: "water", nadeType: "flash", 
  throwType: "run", side: "CT", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/ae4hsy/mp4.mp4"},
  { id: "overpass_popflash_long_2", title: "Popflash long 2", startingLocation: "long?", nadeType: "flash", //change
  throwType: "normal", side: "CT", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/gqg7y8/mp4.mp4"},
  { id: "overpass_popflash_monster_from_back_site", title: "Popflash monster", startingLocation: "back B site", nadeType: "flash", 
  throwType: "normal", side: "CT", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/n1pinx/mp4.mp4"},
  { id: "overpass_popflash_through_pipe_smoke", title: "Popflash through smoke", startingLocation: "water", nadeType: "flash", 
  throwType: "right click", side: "T", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/xshums/mp4.mp4"},
  { id: "overpass_popflash_pipe", title: "Popflash pipe", startingLocation: "B short", nadeType: "flash", 
  throwType: "run, right click", side: "T", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/e9eqgd/mp4.mp4"},
  { id: "overpass_popflash_front_bathrooms_from_truck", title: "Popflash front bathrooms", startingLocation: "truck", nadeType: "flash", 
  throwType: "normal", side: "CT", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/2tb2cc/mp4.mp4"},
  { id: "overpass_nade_monster_ct", title: "Nade monster", startingLocation: "lower", nadeType: "he", 
  throwType: "normal", side: "CT", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/mmxco7/mp4.mp4"},
  { id: "overpass_nade_playground_from_bathrooms", title: "Nade playground", startingLocation: "bathrooms", nadeType: "he", 
  throwType: "run+jump", side: "CT", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/f43w0w/mp4.mp4"},
  { id: "overpass_nade_door", title: "Nade connector door", startingLocation: "lower", nadeType: "he", 
  throwType: "normal", side: "CT", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/o6674s/mp4.mp4"},
  { id: "overpass_nade_connector_door_easy", title: "Nade connector door (easy)", startingLocation: "lower", nadeType: "he", 
  throwType: "normal", side: "CT", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/nbgboj/mp4.mp4"},
  { id: "overpass_molly_headshot", title: "Molly headshot", startingLocation: "water", nadeType: "molly", 
  throwType: "normal", side: "T", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/2fpukn/mp4.mp4"},
  { id: "overpass_molly_short_control", title: "Molly short", startingLocation: "control room", nadeType: "molly", 
  throwType: "normal", side: "CT", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/lhvnwx/mp4.mp4"},
  { id: "overpass_molly_dumpster_from_top_connector", title: "Molly dumpster", startingLocation: "top connector", nadeType: "molly", 
  throwType: "run+jump", side: "T", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/0u9k51/mp4.mp4"},
  { id: "overpass_molly_toxic_from_back_water", title: "Molly toxic", startingLocation: "back water", nadeType: "molly", 
  throwType: "quick run", side: "T", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/4e52cf/mp4.mp4"},
  { id: "overpass_molly_lower_from_monster", title: "Molly lower", startingLocation: "monster", nadeType: "molly", 
  throwType: "run", side: "T", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/n05el5/mp4.mp4"},
  { id: "overpass_molly_party_from_back_playground", title: "Molly party", startingLocation: "back playground", nadeType: "molly", 
  throwType: "jump", side: "T", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/j2cm3d/mp4.mp4"},
  { id: "overpass_molly_short_quick", title: "Molly short (quick)", startingLocation: "T spawn", nadeType: "molly", 
  throwType: "run", side: "T", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/cfdzzg/mp4.mp4"},
  { id: "overpass_molly_truck_from_long", title: "Molly truck", startingLocation: "long", nadeType: "molly", 
  throwType: "run", side: "T", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/dk4hvb/mp4.mp4"},
  { id: "overpass_molly_truck_from_short", title: "Molly truck", startingLocation: "A short", nadeType: "molly", 
  throwType: "jump", side: "T", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/8z2jah/mp4.mp4"},
  { id: "overpass_molly_barrels_from_water", title: "Molly toxic", startingLocation: "water", nadeType: "molly", 
  throwType: "jump", side: "T", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/knz0et/mp4.mp4"},
  { id: "overpass_molly_deep_playground", title: "Molly deep playground", startingLocation: "divider", nadeType: "molly", 
  throwType: "run+jump", side: "CT", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/cip7i4/mp4.mp4"},
  { id: "overpass_lurk_b_smoke", title: "B lurk smoke", startingLocation: "T spawn", nadeType: "smoke", 
  throwType: "normal", side: "T", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/ho8acs/mp4.mp4"},
  { id: "overpass_molly_divider", title: "Molly divider", startingLocation: "fountain", nadeType: "molly", 
  throwType: "quick run", side: "T", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/9rj6vz/mp4.mp4"},
  { id: "overpass_molly_default_a_from_long", title: "Molly dice", startingLocation: "long", nadeType: "molly", 
  throwType: "normal", side: "T", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/d4nas3/mp4.mp4"},
  { id: "overpass_molly_default_a", title: "Molly dice", startingLocation: "divider", nadeType: "molly", 
  throwType: "jump", side: "T", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/jub28n/mp4.mp4"},
  { id: "overpass_molly_deep_connector_from_party", title: "Molly deep connector", startingLocation: "party", nadeType: "molly", 
  throwType: "normal", side: "T", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/6h1bvb/mp4.mp4"},
  { id: "overpass_molly_deep_mid", title: "Molly deep mid", startingLocation: "A short", nadeType: "molly", 
  throwType: "run+jump", side: "CT", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/qwxn8u/mp4.mp4"},
  { id: "overpass_flash_mid_from_top_long", title: "Flash mid", startingLocation: "top long", nadeType: "flash", 
  throwType: "normal", side: "T", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/pwaoj9/mp4.mp4"},
  { id: "overpass_flash_long_bathrooms", title: "Flash long bathrooms", startingLocation: "long", nadeType: "flash", 
  throwType: "run", side: "T", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/db1wq7/mp4.mp4"},
  { id: "overpass_flash_support_short", title: "Support flash short", startingLocation: "below heaven", nadeType: "flash",
  throwType: "run", side: "CT", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/teyfzp/mp4.mp4"},
  { id: "overpass_flash_short_for_rush", title: "Flash short for B rush", startingLocation: "canals", nadeType: "flash",
  throwType: "normal", side: "T", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/yy1222/mp4.mp4"},
  { id: "overpass_flash_party_from_ramp", title: "Flash party", startingLocation: "ramp", nadeType: "flash",
  throwType: "quick run", side: "T", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/wbp1zb/mp4.mp4"},
  { id: "overpass_flash_short_from_connector", title: "Flash short", startingLocation: "connector", nadeType: "flash",
  throwType: "quick run", side: "T", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/dqp91i/mp4.mp4"},
  { id: "overpass_flashes_for_b_execute", title: "Flashes for B execute", startingLocation: "water", nadeType: "flash",
  throwType: "normal", side: "T", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/jukbry/mp4.mp4"},
  { id: "overpass_flash_pop_water", title: "Popflash water", startingLocation: "connector", nadeType: "flash",
  throwType: "normal", side: "T", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/ih99mh/mp4.mp4"},
  { id: "overpass_flash_from_playground", title: "Flash above fountain", startingLocation: "playground", nadeType: "flash",
  throwType: "normal", side: "T", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/v90uxf/mp4.mp4"},
  { id: "overpass_flash_pop_monster_for_t", title: "Nose flash", startingLocation: "canals", nadeType: "flash",
  throwType: "normal", side: "T", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/csmopa/mp4.mp4"},
  { id: "overpass_flash_mid_from_party", title: "Flash mid", startingLocation: "party", nadeType: "flash",
  throwType: "normal", side: "T", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/im84qw/mp4.mp4"},
  { id: "overpass_flash_far_long", title: "Flash long", startingLocation: "playground", nadeType: "flash",
  throwType: "jump", side: "T", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/kzq38s/mp4.mp4"},
  { id: "overpass_flash_front_bathroom_from_party", title: "Flash front bathrooms", startingLocation: "party", nadeType: "flash",
  throwType: "normal", side: "T", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/co9my0/mp4.mp4"},
  { id: "overpass_flash_combo_for_a", title: "Flash combo for A", startingLocation: "A short", nadeType: "flash",
  throwType: "run", side: "T", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/oy0efn/mp4.mp4"},
  { id: "overpass_flash_aggressive_ramp_t", title: "Flash for ramp push", startingLocation: "ramp", nadeType: "flash",
  throwType: "quick run", side: "T", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/xr0gis/mp4.mp4"},
  { id: "overpass_flash_close_long", title: "Flash long", startingLocation: "long", nadeType: "flash",
  throwType: "normal", side: "T", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/vijpvl/mp4.mp4"},
  { id: "overpass_fast_molly_pipe", title: "Molly pipe (fast)", startingLocation: "lower", nadeType: "molly",
  throwType: "run+medium throw", side: "CT", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/6r3mp4/mp4.mp4"},
  { id: "overpass_defensive_long_setup", title: "Defense long smoke", startingLocation: "A site", nadeType: "smoke",
  throwType: "quick run", side: "CT", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/5knvxy/mp4.mp4"},
  { id: "overpass_defensive_smoke_from_long", title: "Defensive A smoke", startingLocation: "long", nadeType: "smoke",
  throwType: "right click", side: "CT", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/43gt0d/mp4.mp4"},
  { id: "overpass_ct_utility_combo_divider", title: "Divider utility", startingLocation: "outside bathrooms", nadeType: "smoke, he",
  throwType: "quick run", side: "CT", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/sucwo2/mp4.mp4"},
  { id: "overpass_back_corner_wallbang", title: "Pipe wallbang", startingLocation: "lower", nadeType: "wallbang",
  throwType: "none", side: "CT", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/153sm7/mp4.mp4"},
  { id: "overpass_boost_connector_for_pipe", title: "Boost for pipe", startingLocation: "connector", nadeType: "boost",
  throwType: "none", side: "all", description: "", map: "overpass", game: "CSGO", contentUrl: "https://streamable.com/l/yfh1n8/mp4.mp4"},

  // *********************************************** CS:GO NUKE ***********************************************

  { id: "nuke_a_exec_back_silo_molly_and_flashes", title: "Back silo molly and flashes", startingLocation: "T roof", nadeType: "molly, flash",
  throwType: "jump", side: "T", description: "", map: "nuke", game: "CSGO", contentUrl: "https://streamable.com/l/bsby8g/mp4.mp4"},
  { id: "nuke_molly_top_hut_and_flashes", title: "Molly top hut and flashes", startingLocation: "T roof", nadeType: "molly, flash",
  throwType: "run+jump", side: "T", description: "The windows need to be shot out first.", map: "nuke", game: "CSGO", contentUrl: "https://streamable.com/l/yc34rg/mp4.mp4"},
  { id: "nuke_smoke_hell_from_outside", title: "Smoke hell", startingLocation: "outside", nadeType: "smoke",
  throwType: "run+jump", side: "T", description: "", map: "nuke", game: "CSGO", contentUrl: "https://streamable.com/l/be7nxc/mp4.mp4"},
  { id: "nuke_smoke_mini_from_silo", title: "Smoke mini", startingLocation: "silo", nadeType: "smoke",
  throwType: "run", side: "T", description: "", map: "nuke", game: "CSGO", contentUrl: "https://streamable.com/l/grplil/mp4.mp4"},
  { id: "nuke_molly_top_hut_and_flash", title: "Molly top hut and flash", startingLocation: "T roof", nadeType: "molly, flash",
  throwType: "jump", side: "T", description: "", map: "nuke", game: "CSGO", contentUrl: "https://streamable.com/l/o91oeu/mp4.mp4"},
  { id: "nuke_vent_rush_utility", title: "Vent rush utility", startingLocation: "lobby", nadeType: "smoke, he",
  throwType: "run, right click", side: "T", description: "", map: "nuke", game: "CSGO", contentUrl: "https://streamable.com/l/51w35n/mp4.mp4"},
  { id: "nuke_vent_smoke", title: "Vent smoke and HE", startingLocation: "lobby", nadeType: "smoke, he",
  throwType: "run", side: "T", description: "", map: "nuke", game: "CSGO", contentUrl: "https://streamable.com/l/xdilpi/mp4.mp4"},
  { id: "nuke_vent_rush_smoke_from_spawn", title: "Vent rush smoke", startingLocation: "T spawn", nadeType: "smoke",
  throwType: "jump", side: "T", description: "", map: "nuke", game: "CSGO", contentUrl: "https://streamable.com/l/3r58sp/mp4.mp4"},
  { id: "nuke_smokewall_from_outside2", title: "Smokewall 2", startingLocation: "outside", nadeType: "smoke",
  throwType: "normal", side: "T", description: "", map: "nuke", game: "CSGO", contentUrl: "https://streamable.com/l/a7anr0/mp4.mp4"},
  { id: "nuke_smokewall_from_spawn2", title: "Smokewall 2", startingLocation: "outside", nadeType: "smoke",
  throwType: "jump", side: "T", description: "", map: "nuke", game: "CSGO", contentUrl: "https://streamable.com/l/podzn6/mp4.mp4"},
  { id: "nuke_smokewall_from_spawn1", title: "Smokewall 1", startingLocation: "T spawn", nadeType: "smoke",
  throwType: "jump", side: "T", description: "", map: "nuke", game: "CSGO", contentUrl: "https://streamable.com/l/oyn39o/mp4.mp4"},
  { id: "nuke_smoke_outside_to_peek_silo", title: "Smoke outside (gla1ve smoke)", startingLocation: "CT spawn", nadeType: "smoke",
  throwType: "run", side: "CT", description: "", map: "nuke", game: "CSGO", contentUrl: "https://streamable.com/l/bo4ejx/mp4.mp4"},
  { id: "nuke_smoke_a_main_from_outside_closer", title: "Smoke A main", startingLocation: "outside A main", nadeType: "smoke",
  throwType: "run", side: "T", description: "", map: "nuke", game: "CSGO", contentUrl: "https://streamable.com/l/rg34yc/mp4.mp4"},
  { id: "nuke_smoke_squeaky_from_heaven", title: "Smoke squeaky", startingLocation: "heaven", nadeType: "smoke",
  throwType: "normal", side: "CT", description: "", map: "nuke", game: "CSGO", contentUrl: "https://streamable.com/l/t7jkuj/mp4.mp4"},
  { id: "nuke_smokewall_from_outside1", title: "Smokewall 1", startingLocation: "outside", nadeType: "smoke",
  throwType: "normal", side: "T", description: "", map: "nuke", game: "CSGO", contentUrl: "https://streamable.com/l/6zz7z9/mp4.mp4"},
  { id: "nuke_smoke_garage", title: "Smoke garage", startingLocation: "outside", nadeType: "smoke",
  throwType: "normal", side: "T", description: "", map: "nuke", game: "CSGO", contentUrl: "https://streamable.com/l/lrftb5/mp4.mp4"},
  { id: "nuke_smoke_default", title: "Smoke default", startingLocation: "vending", nadeType: "smoke",
  throwType: "walk", side: "T", description: "", map: "nuke", game: "CSGO", contentUrl: "https://streamable.com/l/a71jmu/mp4.mp4"},
  { id: "nuke_smoke_a_main_from_outside", title: "Smoke A main", startingLocation: "outside", nadeType: "smoke",
  throwType: "run", side: "T", description: "", map: "nuke", game: "CSGO", contentUrl: "https://streamable.com/l/wih1a2/mp4.mp4"},
  { id: "nuke_smoke_a_main", title: "Smoke A main (and HE)", startingLocation: "lobby", nadeType: "smoke, he",
  throwType: "run", side: "T", description: "", map: "nuke", game: "CSGO", contentUrl: "https://streamable.com/l/361awx/mp4.mp4"},
  { id: "nuke_ramp_lamp_flash", title: "Lamp flash", startingLocation: "ramp", nadeType: "flash",
  throwType: "normal", side: "T", description: "", map: "nuke", game: "CSGO", contentUrl: "https://streamable.com/l/w8p5ir/mp4.mp4"},
  { id: "nuke_pop_flash_vent", title: "Popflash vent", startingLocation: "A site", nadeType: "flash",
  throwType: "right click", side: "all", description: "", map: "nuke", game: "CSGO", contentUrl: "https://streamable.com/l/jh1nlq/mp4.mp4"},
  { id: "nuke_ramp_anti_rush_utility", title: "Anti-rush utility", startingLocation: "ramp", nadeType: "smoke, he",
  throwType: "run", side: "CT", description: "", map: "nuke", game: "CSGO", contentUrl: "https://streamable.com/l/jacijo/mp4.mp4"},
  { id: "nuke_ramp_utility_set_t_side", title: "T side ramp utility", startingLocation: "ramp", nadeType: "smoke, flash",
  throwType: "normal, run", side: "T", description: "", map: "nuke", game: "CSGO", contentUrl: "https://streamable.com/l/cf437x/mp4.mp4"},
  { id: "nuke_molly_dark", title: "Molly dark", startingLocation: "below ramp", nadeType: "molly",
  throwType: "normal", side: "all", description: "", map: "nuke", game: "CSGO", contentUrl: "https://streamable.com/l/fcyeu2/mp4.mp4"},
  { id: "nuke_molly_for_ct_hut_rush", title: "Fake hut molly", startingLocation: "heaven", nadeType: "molly",
  throwType: "normal", side: "CT", description: "", map: "nuke", game: "CSGO", contentUrl: "https://streamable.com/l/qfw07l/mp4.mp4"},
  { id: "nuke_molly_double_doors", title: "Molly double doors", startingLocation: "below ramp", nadeType: "molly",
  throwType: "quick run", side: "T", description: "", map: "nuke", game: "CSGO", contentUrl: "https://streamable.com/l/4kls5n/mp4.mp4"},
  { id: "nuke_molly_behind_blue_box_two_ways", title: "Molly behind blue box", startingLocation: "top mini", nadeType: "molly",
  throwType: "run", side: "T", description: "", map: "nuke", game: "CSGO", contentUrl: "https://streamable.com/l/f4ei5v/mp4.mp4"},
  { id: "nuke_molly_secret_from_outside", title: "Molly secret", startingLocation: "outside", nadeType: "molly",
  throwType: "normal", side: "T", description: "", map: "nuke", game: "CSGO", contentUrl: "https://streamable.com/l/rutfhq/mp4.mp4"},
  { id: "nuke_mini_smoke_utility_combo_from_top_mini", title: "Top mini utility", startingLocation: "top mini", nadeType: "smoke, molly, flash",
  throwType: "normal, run", side: "T", description: "", map: "nuke", game: "CSGO", contentUrl: "https://streamable.com/l/7qm2bt/mp4.mp4"},
  { id: "nuke_molly_squeaky_from_heaven", title: "Molly squeaky", startingLocation: "heaven", nadeType: "molly",
  throwType: "run", side: "CT", description: "", map: "nuke", game: "CSGO", contentUrl: "https://streamable.com/l/tkkzmi/mp4.mp4"},
  { id: "nuke_molly_outside_prevent_rush", title: "Molly outside anti-rush", startingLocation: "CT spawn", nadeType: "molly",
  throwType: "walk+jump", side: "CT", description: "", map: "nuke", game: "CSGO", contentUrl: "https://streamable.com/l/f9cw0i/mp4.mp4"},
  { id: "nuke_molly_silo", title: "Molly silo", startingLocation: "blue box", nadeType: "molly",
  throwType: "jump", side: "CT", description: "", map: "nuke", game: "CSGO", contentUrl: "https://streamable.com/l/k9lge2/mp4.mp4"},
  { id: "nuke_flash_to_cross_to_secret", title: "Flash to cross secret", startingLocation: "outside", nadeType: "flash",
  throwType: "run", side: "CT", description: "", map: "nuke", game: "CSGO", contentUrl: "https://streamable.com/l/absc96/mp4.mp4"},
  { id: "nuke_flash_outside_start_of_round", title: "Flash outside", startingLocation: "CT spawn", nadeType: "flash",
  throwType: "run", side: "CT", description: "", map: "nuke", game: "CSGO", contentUrl: "https://streamable.com/l/2pxt96/mp4.mp4"},
  { id: "nuke_defensive_ramp_molly", title: "Defensive ramp molly", startingLocation: "ramp", nadeType: "molly",
  throwType: "normal", side: "CT", description: "", map: "nuke", game: "CSGO", contentUrl: "https://streamable.com/l/jz3hs3/mp4.mp4"},
  { id: "nuke_deep_smokewall_pair", title: "Deep smokewall pair", startingLocation: "outside", nadeType: "smoke",
  throwType: "jump", side: "T", description: "", map: "nuke", game: "CSGO", contentUrl: "https://streamable.com/l/u43ov9/mp4.mp4"},
  { id: "nuke_cheeky_ramp_smoke", title: "Ramp smoke using gap", startingLocation: "ramp", nadeType: "smoke",
  throwType: "normal", side: "CT", description: "", map: "nuke", game: "CSGO", contentUrl: "https://streamable.com/l/k739n5/mp4.mp4"},
  { id: "nuke_aleksib_cross_smoke", title: "Cross smoke", startingLocation: "T spawn", nadeType: "smoke",
  throwType: "run", side: "T", description: "", map: "nuke", game: "CSGO", contentUrl: "https://streamable.com/l/6ytgay/mp4.mp4"},
  { id: "nuke_a_exec_molly_fake_vent", title: "Molly fake vent", startingLocation: "lobby", nadeType: "molly",
  throwType: "quick run", side: "T", description: "", map: "nuke", game: "CSGO", contentUrl: "https://streamable.com/l/6myq1k/mp4.mp4"},
  { id: "nuke_a_exec_heaven_smoke_mustang_molly", title: "Heaven smoke + mustang molly", startingLocation: "silo", nadeType: "smoke, molly",
  throwType: "normal", side: "T", description: "", map: "nuke", game: "CSGO", contentUrl: "https://streamable.com/l/1h9sl3/mp4.mp4"},
  { id: "nuke_a_exec_back_silo_molly_and_flashes", title: "Back silo molly and flashes", startingLocation: "T roof", nadeType: "flash, molly",
  throwType: "jump", side: "T", description: "", map: "nuke", game: "CSGO", contentUrl: "https://streamable.com/l/1o6rhn/mp4.mp4"},

  // *********************************************** CS:GO MIRAGE ***********************************************

  { id: "mirage_easy_smoke_cross_from_top_mid", title: "Cross smoke", startingLocation: "top mid", nadeType: "smoke",
  throwType: "normal", side: "T", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/ai6y3u/mp4.mp4"},
  { id: "mirage_b_retake_smoke_from_market", title: "B retake smoke", startingLocation: "market", nadeType: "smoke",
  throwType: "normal", side: "all", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/3ldmfe/mp4.mp4"},
  { id: "mirage_t_ramp_lurk_smoke", title: "T ramp lurk smoke", startingLocation: "ramp", nadeType: "smoke",
  throwType: "normal", side: "T", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/k32da0/mp4.mp4"},
  { id: "mirage_smoke_top_connector_from_mid", title: "Top connector smoke", startingLocation: "mid", nadeType: "smoke",
  throwType: "quick run", side: "T", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/aooatj/mp4.mp4"},
  { id: "mirage_smoke_top_connector_from_top_mid", title: "Smoke top connector", startingLocation: "top mid", nadeType: "smoke",
  throwType: "jump", side: "T", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/zd0d41/mp4.mp4"},
  { id: "mirage_smoke_top_connector_from_spawn", title: "Smoke top connector", startingLocation: "T spawn", nadeType: "smoke",
  throwType: "crouch+jump", side: "T", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/ykwbo7/mp4.mp4"},
  { id: "mirage_smoke_left_side_arch", title: "Smoke left side arch", startingLocation: "outside back apts", nadeType: "smoke",
  throwType: "jump", side: "T", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/qdpqe0/mp4.mp4"},
  { id: "mirage_smoke_catwalk_rail", title: "Smoke catwalk rail", startingLocation: "T spawn", nadeType: "smoke",
  throwType: "jump", side: "T", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/97a4zm/mp4.mp4"},
  { id: "mirage_smoke_mid_window_from_top_mid_quick", title: "Smoke window (quick)", startingLocation: "top mid", nadeType: "smoke",
  throwType: "run", side: "T", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/p9wlwj/mp4.mp4"},
  { id: "mirage_smoke_mid_window", title: "Smoke window (lineup)", startingLocation: "top mid", nadeType: "smoke",
  throwType: "normal", side: "T", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/eluhea/mp4.mp4"},
  { id: "mirage_smoke_mid_window_from_spawn_alternate", title: "Smoke window from spawn (alternate)", startingLocation: "T spawn", nadeType: "smoke",
  throwType: "jump throw", side: "T", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/nxcj9t/mp4.mp4"}, //this should probably have a new throw category
  { id: "mirage_smoke_market_window", title: "Smoke market window", startingLocation: "apartments", nadeType: "smoke",
  throwType: "jump", side: "T", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/3qee3m/mp4.mp4"},
  { id: "mirage_smoke_market_door", title: "Smoke market door", startingLocation: "apartments", nadeType: "smoke",
  throwType: "jump", side: "T", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/fqk0dl/mp4.mp4"},
  { id: "mirage_smoke_palace_from_outside_market", title: "Smoke palace", startingLocation: "outside market", nadeType: "smoke",
  throwType: "jump", side: "CT", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/9n6b0g/mp4.mp4"},
  { id: "mirage_smoke_stairs", title: "Smoke stairs", startingLocation: "ramp", nadeType: "smoke",
  throwType: "normal", side: "T", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/owfmgy/mp4.mp4"},
  { id: "mirage_smoke_right_side_arch", title: "Smoke right side arch", startingLocation: "outside back apts", nadeType: "smoke",
  throwType: "jump", side: "T", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/k60j4n/mp4.mp4"},
  { id: "mirage_smoke_safe_a_ramp", title: "Safe A ramp smoke", startingLocation: "ticket", nadeType: "smoke",
  throwType: "normal", side: "CT", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/80rvjf/mp4.mp4"},
  { id: "mirage_smoke_mid_window_alternate", title: "Smoke window", startingLocation: "T spawn", nadeType: "smoke", //which is actually alternate???
  throwType: "run+jump", side: "T", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/1r67xf/mp4.mp4"},
  { id: "mirage_smoke_jungle_from_site", title: "Smoke jungle", startingLocation: "A site", nadeType: "smoke",
  throwType: "normal", side: "T", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/kvcnws/mp4.mp4"},
  { id: "mirage_smoke_jungle", title: "Smoke jungle", startingLocation: "ramp", nadeType: "smoke",
  throwType: "normal", side: "T", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/awtf6f/mp4.mp4"},
  { id: "mirage_smoke_top_mid", title: "Smoke top mid", startingLocation: "T spawn", nadeType: "smoke",
  throwType: "normal", side: "T", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/y0qnzp/mp4.mp4"}, //might wanna get rid of this
  { id: "mirage_smoke_go_catwalk", title: "Run up catwalk smoke", startingLocation: "catwalk", nadeType: "smoke",
  throwType: "right click", side: "T", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/h9mgpu/mp4.mp4"},
  { id: "mirage_smoke_ct_from_site", title: "Smoke CT", startingLocation: "A site", nadeType: "smoke",
  throwType: "normal", side: "T", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/sln3kn/mp4.mp4"},
  { id: "mirage_smoke_ct_best", title: "Smoke CT", startingLocation: "T spawn", nadeType: "smoke",
  throwType: "jump", side: "T", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/yc8o7m/mp4.mp4"},
  { id: "mirage_smoke_ct", title: "Smoke CT", startingLocation: "T spawn", nadeType: "smoke",
  throwType: "jump", side: "T", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/un2flw/mp4.mp4"},
  { id: "mirage_smoke_connector_from_palace", title: "Smoke connector", startingLocation: "palace", nadeType: "smoke",
  throwType: "normal", side: "T", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/7hrmkw/mp4.mp4"},
  { id: "mirage_smoke_catwalk_from_underpass", title: "Smoke catwalk", startingLocation: "underpass", nadeType: "smoke",
  throwType: "normal", side: "T", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/u4ebp0/mp4.mp4"},
  { id: "mirage_smoke_catwalk_from_t_spawn", title: "Smoke catwalk", startingLocation: "T spawn", nadeType: "smoke",
  throwType: "jump", side: "T", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/ie9vsm/mp4.mp4"},
  { id: "mirage_smoke_catwalk", title: "Smoke catwalk", startingLocation: "top mid", nadeType: "smoke",
  throwType: "normal", side: "T", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/s56sm7/mp4.mp4"},
  { id: "mirage_smoke_connector_from_a_site", title: "Smoke connector", startingLocation: "A site", nadeType: "smoke",
  throwType: "normal", side: "T", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/yptqcn/mp4.mp4"},
  { id: "mirage_smoke_bench_deep_apts", title: "Smoke bench", startingLocation: "apartments", nadeType: "smoke",
  throwType: "normal", side: "T", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/d028mg/mp4.mp4"},
  { id: "mirage_ramp_retake_utility", title: "Ramp retake utility", startingLocation: "jungle", nadeType: "smoke, molly",
  throwType: "normal", side: "CT", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/cgeix1/mp4.mp4"},
  { id: "mirage_smoke_balcony", title: "Smoke balcony", startingLocation: "apartments", nadeType: "smoke",
  throwType: "jump", side: "T", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/6dkb06/mp4.mp4"},
  { id: "mirage_retake_utility_from_van_1", title: "Retake utility from van", startingLocation: "van", nadeType: "smoke, molly, he",
  throwType: "normal", side: "all", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/5z1tfe/mp4.mp4"},
  { id: "mirage_quick_smoke_ramp", title: "Quick smoke ramp", startingLocation: "CT spawn", nadeType: "smoke",
  throwType: "jump", side: "CT", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/aky4pk/mp4.mp4"},
  { id: "mirage_smoke_arches", title: "Smoke arch", startingLocation: "apartments", nadeType: "smoke",
  throwType: "normal", side: "T", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/f3gcom/mp4.mp4"},
  { id: "mirage_popflash_stairs", title: "Popflash stairs", startingLocation: "stairs", nadeType: "flash",
  throwType: "run", side: "CT", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/bda1n8/mp4.mp4"},
  { id: "mirage_molly_jungle_from_palace", title: "Molly jungle", startingLocation: "palace", nadeType: "molly",
  throwType: "quick run", side: "T", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/6h26ly/mp4.mp4"},
  { id: "mirage_molly_ramp_from_jungle", title: "Molly ramp", startingLocation: "jungle", nadeType: "molly",
  throwType: "normal", side: "CT", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/m99o99/mp4.mp4"},
  { id: "mirage_molly_jungle", title: "Molly jungle", startingLocation: "jungle", nadeType: "molly",
  throwType: "run", side: "T", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/l6dr8y/mp4.mp4"},
  { id: "mirage_molly_edward_from_cat", title: "Molly Edward", startingLocation: "catwalk", nadeType: "molly",
  throwType: "normal", side: "all", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/13572j/mp4.mp4"},
  { id: "mirage_flash_to_peek_mid_for_catwalk", title: "Peek mid flash", startingLocation: "catwalk", nadeType: "flash",
  throwType: "run", side: "CT", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/i2odst/mp4.mp4"},
  { id: "mirage_molly_bench_from_apts", title: "Molly bench", startingLocation: "apartments", nadeType: "molly",
  throwType: "run", side: "T", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/w5ywa8/mp4.mp4"},
  { id: "mirage_molly_b_site_default_from_apts", title: "Molly B site default", startingLocation: "apartments", nadeType: "molly",
  throwType: "normal", side: "T", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/xe2jx2/mp4.mp4"},
  { id: "mirage_flash_retake_ticket_booth", title: "Retake flash", startingLocation: "ticket booth", nadeType: "flash",
  throwType: "normal", side: "CT", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/molo4k/mp4.mp4"},
  { id: "mirage_flash_ramp", title: "Flash ramp", startingLocation: "under palace", nadeType: "flash",
  throwType: "jump", side: "CT", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/kfuj3w/mp4.mp4"},
  { id: "mirage_flash_pop_palace", title: "Popflash A site", startingLocation: "palace", nadeType: "flash",
  throwType: "quick run", side: "T", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/7xi7wq/mp4.mp4"},
  { id: "mirage_conP_smoke_for_mid_aggression", title: "Smoke for mid aggression", startingLocation: "connector", nadeType: "smoke",
  throwType: "run", side: "CT", description: "Peek out of this somke with a flash over mid from a teammate.", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/552pq0/mp4.mp4"},
  { id: "mirage_flash_market_door_retake", title: "Retake flash for B", startingLocation: "market door", nadeType: "flash",
  throwType: "normal", side: "CT", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/qpoeez/mp4.mp4"},
  { id: "mirage_flash_cross_connector", title: "Cross connector flash", startingLocation: "catwalk", nadeType: "flash",
  throwType: "normal", side: "T", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/o2p9f2/mp4.mp4"},
  { id: "mirage_flash_cat_from_back_apts", title: "Flash cat", startingLocation: "back apts", nadeType: "flash",
  throwType: "jump", side: "T", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/z99owt/mp4.mp4"},
  { id: "mirage_conP_molly_ramp", title: "Molly ramp", startingLocation: "ticket booth", nadeType: "molly",
  throwType: "run", side: "CT", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/mrq4vy/mp4.mp4"},
  { id: "mirage_flash_peek_mid", title: "Peek mid flash", startingLocation: "top mid", nadeType: "flash",
  throwType: "normal", side: "T", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/3r7yp1/mp4.mp4"},
  { id: "mirage_b_anchor_setup_delayed", title: "B anchor setup", startingLocation: "van", nadeType: "smoke, flash",
  throwType: "run, normal", side: "CT", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/vm8el1/mp4.mp4"},
  { id: "mirage_b_anchor_setup_counter_awp_pick", title: "Counter AWP util", startingLocation: "van", nadeType: "molly, he",
  throwType: "quick run, run", side: "CT", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/as297x/mp4.mp4"},
  { id: "mirage_molly_dark_from_palace", title: "Molly dark", startingLocation: "palace", nadeType: "molly",
  throwType: "run", side: "T", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/ikmi5z/mp4.mp4"},
  { id: "mirage_molly_connector_from_mid", title: "Molly connector from mid", startingLocation: "mid", nadeType: "molly",
  throwType: "run", side: "T", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/q7s23j/mp4.mp4"},
  { id: "mirage_smoke_cross", title: "Smoke cross", startingLocation: "T spawn", nadeType: "smoke",
  throwType: "normal", side: "T", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/meeh9x/mp4.mp4"},
  { id: "mirage_flash_pop_b", title: "Popflash B site", startingLocation: "inside apts", nadeType: "flash",
  throwType: "run", side: "T", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/60rq7l/mp4.mp4"},
  { id: "mirage_smoke_bench", title: "Smoke bench", startingLocation: "inside apts", nadeType: "smoke",
  throwType: "normal", side: "T", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/qmkbwl/mp4.mp4"},
  { id: "mirage_smoke_b_apts", title: "Smoke B apts", startingLocation: "trash can", nadeType: "smoke",
  throwType: "normal", side: "CT", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/rv3bll/mp4.mp4"},
  { id: "mirage_catP_smoke_mid_catwalk_for_ct", title: "Mid catwalk smoke", startingLocation: "catwalk", nadeType: "smoke",
  throwType: "normal", side: "CT", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/rz4ugs/mp4.mp4"},
  { id: "mirage_catwalk_utility_set_ct", title: "Catwalk CT utility", startingLocation: "catwalk", nadeType: "smoke, molly, flash",
  throwType: "normal, quick run", side: "CT", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/kx2t47/mp4.mp4"},
  { id: "mirage_conP_molly_palace", title: "Molly palace", startingLocation: "connector", nadeType: "molly",
  throwType: "normal", side: "CT", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/fbeydz/mp4.mp4"},
  { id: "mirage_bench_boost_setup", title: "Bench boost", startingLocation: "B bench", nadeType: "boost",
  throwType: "none", side: "CT", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/nuf2vm/mp4.mp4"},
  { id: "mirage_b_afterplant_utility", title: "B afterplant utility", startingLocation: "B site", nadeType: "molly, smoke, flash",
  throwType: "jump", side: "T", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/qxgyxf/mp4.mp4"},
  { id: "mirage_b_retake_flashes_from_back_market", title: "B retake flashes", startingLocation: "outside market", nadeType: "flash",
  throwType: "jump", side: "CT", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/5em7g5/mp4.mp4"},
  { id: "mirage_utility_set_from_tetris_t", title: "Utility set for T", startingLocation: "tetris", nadeType: "molly, flash, he",
  throwType: "jump, run", side: "T", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/zstrju/mp4.mp4"},
  { id: "mirage_aggressive_mid_flash_thru_connector", title: "Mid support flash thru connector", startingLocation: "A site", nadeType: "flash",
  throwType: "normal", side: "CT", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/p4slc0/mp4.mp4"},
  { id: "mirage_a_retake_utility_from_ticket", title: "Retake utility", startingLocation: "ticket", nadeType: "molly, flash, he",
  throwType: "jump, normal, run", side: "CT", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/9tdny1/mp4.mp4"},
  { id: "mirage_support_flash_ct_for_t", title: "Support flash CT for T", startingLocation: "A site", nadeType: "flash",
  throwType: "normal", side: "T", description: "", map: "mirage", game: "CSGO", contentUrl: "https://streamable.com/l/bciwkg/mp4.mp4"},

  // *********************************************** CS:GO INFERNO ***********************************************

  { id: "inferno_anti_rush_b_flash", title: "Anti B rush flash and molly", startingLocation: "Top banana", nadeType: "molly, flash", throwType: "run, jump", side: "CT", description: "", map: "inferno", game: "CSGO", contentUrl: "https://streamable.com/l/ehsrjb/mp4.mp4"},
  { id: "inferno_apts_oneway_smoke", title: "Apts one-way smoke", startingLocation: "apts", nadeType: "smoke", throwType: "crouch+normal", side: "T", description: "", map: "inferno", game: "CSGO", contentUrl: "https://streamable.com/l/v09pp7/mp4.mp4"},
  { id: "inferno_back_site_retake_molly_from_arch", title: "Back A site retake molly", startingLocation: "Arch", nadeType: "molly", throwType: "jump", side: "CT", description: "", map: "inferno", game: "CSGO", contentUrl: "https://streamable.com/l/0j8z55/mp4.mp4"},
  { id: "inferno_banana_utility_set_from_coffin", title: "Banana utility set", startingLocation: "coffin", nadeType: "molly, flash, smoke", throwType: "jump", side: "CT", description: "", map: "inferno", game: "CSGO", contentUrl: "https://streamable.com/l/0vbn2l/mp4.mp4"},
  { id: "inferno_fake_molly_and_arch_smoke", title: "Fake molly and arch smoke", startingLocation: "second mid", nadeType: "molly, smoke, flash", throwType: "jump", side: "T", description: "", map: "inferno", game: "CSGO", contentUrl: "https://streamable.com/l/4110gu/mp4.mp4"},
  { id: "inferno_fast_smoke_long", title: "Fast smoke long", startingLocation: "T spawn", nadeType: "smoke", throwType: "walk+jump", side: "T", description: "", map: "inferno", game: "CSGO", contentUrl: "https://streamable.com/l/qas1e9/mp4.mp4"},    
  { id: "inferno_fast_smoke_short", title: "Fast short smoke", startingLocation: "T spawn", nadeType: "smoke", throwType: "jump", side: "T", description: "", map: "inferno", game: "CSGO", contentUrl: "https://streamable.com/l/zg1uuy/mp4.mp4"},
  // { id: "inferno_furia_oneway_smoke", title: "XXXX", startingLocation: "XXXX", nadeType: "XXXX", throwType: "XXXX", side: "XXXX", description: "", map: "inferno", game: "CSGO", contentUrl: "XXXXXX"},
  { id: "inferno_god_flash_a_peek_boiler", title: "Peek boiler flash (god flash)", startingLocation: "mid", nadeType: "flash", throwType: "jump", side: "T", description: "", map: "inferno", game: "CSGO", contentUrl: "https://streamable.com/l/0uhwjd/mp4.mp4"},
  { id: "inferno_god_flash_b", title: "God flash for B", startingLocation: "banana", nadeType: "flash", throwType: "jump", side: "T", description: "", map: "inferno", game: "CSGO", contentUrl: "https://streamable.com/l/wjx308/mp4.mp4"},
  { id: "inferno_jump_peek_banana_with_nade", title: "Jump peek banana with nade", startingLocation: "top banana", nadeType: "molly, he", throwType: "run", side: "CT", description: "", map: "inferno", game: "CSGO", contentUrl: "https://streamable.com/l/3dugc0/mp4.mp4"},
  { id: "inferno_molly_and_nade_grill", title: "Molly and nade grill", startingLocation: "sandbags", nadeType: "molly, he", throwType: "jump", side: "CT", description: "", map: "inferno", game: "CSGO", contentUrl: "https://streamable.com/l/yauxh4/mp4.mp4"},
  { id: "inferno_molly_balcony_side_apartments_and_flash", title: "Molly balcony side apartments", startingLocation: "second mid", nadeType: "molly, flash", throwType: "run+jump, normal", side: "T", description: "", map: "inferno", game: "CSGO", contentUrl: "https://streamable.com/l/b7akw7/mp4.mp4"},
  { id: "inferno_molly_banana_standard_ct", title: "Standard banana molly", startingLocation: "Top banana", nadeType: "molly", throwType: "normal", side: "CT", description: "", map: "inferno", game: "CSGO", contentUrl: "https://streamable.com/l/sf7i5c/mp4.mp4"},
  { id: "inferno_molly_car_t", title: "Molly car", startingLocation: "bottom banana", nadeType: "molly", throwType: "run", side: "T", description: "", map: "inferno", game: "CSGO", contentUrl: "https://streamable.com/l/ycz588/mp4.mp4"},
  { id: "inferno_molly_close_banana_1_ct", title: "Molly close banana (super quick)", startingLocation: "top banana", nadeType: "molly", throwType: "jump", side: "CT", description: "", map: "inferno", game: "CSGO", contentUrl: "https://streamable.com/l/cjrk26/mp4.mp4"},
  { id: "inferno_molly_mid_banana_ct", title: "Molly mid banana", startingLocation: "top banana", nadeType: "molly", throwType: "normal", side: "CT", description: "", map: "inferno", game: "CSGO", contentUrl: "https://streamable.com/l/aa2w0g/mp4.mp4"},
  { id: "inferno_molly_new_box_easy", title: "Easy quad molly", startingLocation: "lane", nadeType: "molly", throwType: "normal", side: "T", description: "", map: "inferno", game: "CSGO", contentUrl: "https://streamable.com/l/ygezqh/mp4.mp4"},
  { id: "inferno_molly_patio", title: "Molly patio", startingLocation: "bench", nadeType: "molly", throwType: "forward+jump", side: "T", description: "", map: "inferno", game: "CSGO", contentUrl: "https://streamable.com/l/muxfj4/mp4.mp4"},
  { id: "inferno_molly_quad_from_banana_t", title: "Molly quad", startingLocation: "car", nadeType: "molly", throwType: "jump", side: "T", description: "", map: "inferno", game: "CSGO", contentUrl: "https://streamable.com/l/5iwk4u/mp4.mp4"},
  { id: "inferno_molly_retake_dark_from_construction_ct", title: "Retake dark", startingLocation: "construction", nadeType: "molly", throwType: "run+jump", side: "CT", description: "", map: "inferno", game: "CSGO", contentUrl: "https://streamable.com/l/b2vbsp/mp4.mp4"},
  { id: "inferno_molly_second_oranges", title: "Molly second oranges", startingLocation: "car", nadeType: "molly", throwType: "crouch+jump", side: "T", description: "", map: "inferno", game: "CSGO", contentUrl: "https://streamable.com/l/w3g22f/mp4.mp4"},
  { id: "inferno_nade_anti_rush_banana_ct", title: "Anti-rush banana nade", startingLocation: "lane", nadeType: "he", throwType: "normal", side: "CT", description: "", map: "inferno", game: "CSGO", contentUrl: "https://streamable.com/l/3tazq9/mp4.mp4"},
  { id: "inferno_nade_car_from_b_site_ct", title: "Nade car", startingLocation: "B site", nadeType: "he", throwType: "run+jump", side: "CT", description: "", map: "inferno", game: "CSGO", contentUrl: "https://streamable.com/l/lveaaz/mp4.mp4"},
  // { id: "inferno_nade_coffin_from_halfwall", title: "XXXX", startingLocation: "XXXX", nadeType: "XXXX", throwType: "XXXX", side: "XXXX", description: "", map: "inferno", game: "CSGO", contentUrl: "XXXXXX"},
  { id: "inferno_nade_mid", title: "Nade mid", startingLocation: "top mid", nadeType: "he", throwType: "quick run", side: "CT", description: "", map: "inferno", game: "CSGO", contentUrl: "https://streamable.com/l/aeth20/mp4.mp4"},
  // { id: "inferno_oneway_apps_cross_ct", title: "XXXX", startingLocation: "XXXX", nadeType: "XXXX", throwType: "XXXX", side: "XXXX", description: "", map: "inferno", game: "CSGO", contentUrl: "XXXXXX"},
  // { id: "inferno_oneway_apps_t", title: "XXXX", startingLocation: "XXXX", nadeType: "XXXX", throwType: "XXXX", side: "XXXX", description: "", map: "inferno", game: "CSGO", contentUrl: "XXXXXX"},
  // { id: "inferno_oneway_back_banana_ct", title: "XXXX", startingLocation: "XXXX", nadeType: "XXXX", throwType: "XXXX", side: "XXXX", description: "", map: "inferno", game: "CSGO", contentUrl: "XXXXXX"},
  // { id: "inferno_oneway_banana_peek_ct", title: "XXXX", startingLocation: "XXXX", nadeType: "XXXX", throwType: "XXXX", side: "XXXX", description: "", map: "inferno", game: "CSGO", contentUrl: "XXXXXX"},
  // { id: "inferno_oneway_half_wall_ct", title: "XXXX", startingLocation: "XXXX", nadeType: "XXXX", throwType: "XXXX", side: "XXXX", description: "", map: "inferno", game: "CSGO", contentUrl: "XXXXXX"},
  // { id: "inferno_oneway_smoke_counter_patio_molly", title: "XXXX", startingLocation: "XXXX", nadeType: "XXXX", throwType: "XXXX", side: "XXXX", description: "", map: "inferno", game: "CSGO", contentUrl: "XXXXXX"},
  // { id: "inferno_oneway_smoke_porch_from_dark", title: "XXXX", startingLocation: "XXXX", nadeType: "XXXX", throwType: "XXXX", side: "XXXX", description: "", map: "inferno", game: "CSGO", contentUrl: "XXXXXX"},
  { id: "inferno_popflash_aggressive_banana_ct", title: "Popflash banana aggressive", startingLocation: "top banana", nadeType: "flash", throwType: "run", side: "CT", description: "", map: "inferno", game: "CSGO", contentUrl: "https://streamable.com/l/lqfz7f/mp4.mp4"},
  // { id: "inferno_position_hide_graveyard_ct", title: "XXXX", startingLocation: "XXXX", nadeType: "XXXX", throwType: "XXXX", side: "XXXX", description: "", map: "inferno", game: "CSGO", contentUrl: "XXXXXX"},
  { id: "inferno_quick_molly_apartments_t", title: "Quick molly apts", startingLocation: "second mid", nadeType: "molly", throwType: "run+jump", side: "T", description: "", map: "inferno", game: "CSGO", contentUrl: "https://streamable.com/l/qltgxw/mp4.mp4"},
  // { id: "inferno_safe_flash_from_car", title: "XXXX", startingLocation: "XXXX", nadeType: "XXXX", throwType: "XXXX", side: "XXXX", description: "", map: "inferno", game: "CSGO", contentUrl: "XXXXXX"},
  // { id: "inferno_short_oneway_smoke_ct", title: "XXXX", startingLocation: "XXXX", nadeType: "XXXX", throwType: "XXXX", side: "XXXX", description: "", map: "inferno", game: "CSGO", contentUrl: "XXXXXX"},
  { id: "inferno_smoke_arch_and_library", title: "Smoke arch and library", startingLocation: "mid", nadeType: "smoke", throwType: "normal, jump", side: "T", description: "", map: "inferno", game: "CSGO", contentUrl: "https://streamable.com/l/f0ep1e/mp4.mp4"},
  { id: "inferno_smoke_ct_easy", title: "Smoke CT (easy)", startingLocation: "half wall", nadeType: "smoke", throwType: "normal", side: "T", description: "", map: "inferno", game: "CSGO", contentUrl: "https://streamable.com/l/nktuzz/mp4.mp4"},
  { id: "inferno_smoke_deep_long", title: "Smoke deep long", startingLocation: "second mid", nadeType: "smoke", throwType: "normal", side: "T", description: "", map: "inferno", game: "CSGO", contentUrl: "https://streamable.com/l/mo9qbf/mp4.mp4"},
  { id: "inferno_smoke_domino", title: "Smoke domino", startingLocation: "bottom mid", nadeType: "smoke", throwType: "jump", side: "T", description: "", map: "inferno", game: "CSGO", contentUrl: "https://streamable.com/l/wvoq9p/mp4.mp4"},
  // { id: "inferno_smoke_fnatic_banana_control_one_way", title: "XXXX", startingLocation: "XXXX", nadeType: "XXXX", throwType: "XXXX", side: "XXXX", description: "", map: "inferno", game: "CSGO", contentUrl: "XXXXXX"},
  { id: "inferno_smoke_halfwall_quick", title: "Smoke halfwall (quick)", startingLocation: "T spawn", nadeType: "smoke", throwType: "run+jump", side: "T", description: "", map: "inferno", game: "CSGO", contentUrl: "https://streamable.com/l/320udy/mp4.mp4"},
  { id: "inferno_smoke_haycart_from_underpass", title: "Smoke haycart", startingLocation: "underpass", nadeType: "smoke", throwType: "jump", side: "T", description: "", map: "inferno", game: "CSGO", contentUrl: "https://streamable.com/l/3hjydy/mp4.mp4"},
  { id: "inferno_smoke_mid_from_pit_ct", title: "Smoke mid", startingLocation: "pit", nadeType: "smoke", throwType: "jump", side: "CT", description: "", map: "inferno", game: "CSGO", contentUrl: "https://streamable.com/l/6sycdd/mp4.mp4"},
  { id: "inferno_smoke_moto", title: "Smoke moto", startingLocation: "mid", nadeType: "smoke", throwType: "normal", side: "T", description: "", map: "inferno", game: "CSGO", contentUrl: "https://streamable.com/l/ez9ua3/mp4.mp4"},
  // { id: "inferno_smoke_motto", title: "XXXX", startingLocation: "XXXX", nadeType: "XXXX", throwType: "XXXX", side: "XXXX", description: "", map: "inferno", game: "CSGO", contentUrl: "XXXXXX"},
  { id: "inferno_smoke_pit_cross", title: "Smoke pit cross", startingLocation: "second mid", nadeType: "smoke", throwType: "normal", side: "T", description: "", map: "inferno", game: "CSGO", contentUrl: "https://streamable.com/l/fwa3c7/mp4.mp4"},
  { id: "inferno_smoke_ruins", title: "Smoke ruins", startingLocation: "banana", nadeType: "smoke", throwType: "normal", side: "T", description: "", map: "inferno", game: "CSGO", contentUrl: "https://streamable.com/l/h0orf1/mp4.mp4"},
  { id: "inferno_smoke_ruins_safe", title: "Smoke ruins (safe)", startingLocation: "banana", nadeType: "smoke", throwType: "normal", side: "T", description: "", map: "inferno", game: "CSGO", contentUrl: "https://streamable.com/l/46bjnt/mp4.mp4"},
  { id: "inferno_smoke_short_safe", title: "Smoke short (safe)", startingLocation: "mid", nadeType: "smoke", throwType: "jump", side: "T", description: "", map: "inferno", game: "CSGO", contentUrl: "https://streamable.com/l/ej1jer/mp4.mp4"},
  { id: "inferno_smoke_short_standard", title: "Smoke long", startingLocation: "bench", nadeType: "smoke", throwType: "run+jump", side: "T", description: "", map: "inferno", game: "CSGO", contentUrl: "https://streamable.com/l/js1iyc/mp4.mp4"},
  { id: "inferno_support_fallen_flash_ct", title: "Fallen flash", startingLocation: "CT", nadeType: "flash", throwType: "crouch+normal", side: "CT", description: "", map: "inferno", game: "CSGO", contentUrl: "https://streamable.com/l/8skxzs/mp4.mp4"},
  { id: "inferno_support_flashes_for_banana_ct", title: "Support flashes for banana", startingLocation: "coffins", nadeType: "flash", throwType: "normal", side: "CT", description: "", map: "inferno", game: "CSGO", contentUrl: "https://streamable.com/l/2mrhzs/mp4.mp4"},
  { id: "inferno_support_flash_bracket_from_bottom_mid", title: "Support flash bracket", startingLocation: "bottom mid", nadeType: "flash", throwType: "normal", side: "T", description: "", map: "inferno", game: "CSGO", contentUrl: "https://streamable.com/l/tognlo/mp4.mp4"},
  { id: "inferno_support_flash_second_mid_ct", title: "Flash second mid", startingLocation: "brackets", nadeType: "flash", throwType: "jump", side: "CT", description: "", map: "inferno", game: "CSGO", contentUrl: "https://streamable.com/l/lar9uh/mp4.mp4"},
  { id: "inferno_triple_nade_porch", title: "Triple nade porch", startingLocation: "banana", nadeType: "he", throwType: "run", side: "T", description: "", map: "inferno", game: "CSGO", contentUrl: "https://streamable.com/l/zaf798/mp4.mp4"},
  { id: "inferno_two_ct_wallbangs_from_apartments", title: "Wallbangs from apts", startingLocation: "apts", nadeType: "molly, wallbang", throwType: "run", side: "CT", description: "", map: "inferno", game: "CSGO", contentUrl: "https://streamable.com/l/09icnq/mp4.mp4"},
  { id: "inferno_t_side_nade_car", title: "Nade car", startingLocation: "bottom banana", nadeType: "he", throwType: "run", side: "T", description: "", map: "inferno", game: "CSGO", contentUrl: "https://streamable.com/l/utb9vq/mp4.mp4"},
  { id: "inferno_utility_set_from_bedroom_balc", title: "Bathroom balc utility set", startingLocation: "bathroom balcony", nadeType: "jump", throwType: "molly, smoke, flash", side: "T", description: "", map: "inferno", game: "CSGO", contentUrl: "https://streamable.com/l/gl4mkz/mp4.mp4"},
    
  // ********************************************** CS2 OVERPASS **********************************************
  { id: "cs2overpass_b_site_god_flash", title: "God flash for B site", startingLocation: "water", nadeType: "flash", throwType: "normal", side: "T", description: "", map: "overpass", game: "CS2", contentUrl: "https://streamable.com/l/nmwb3m/mp4.mp4"},
  { id: "cs2overpass_flash_pillar_from_canals", title: "Flash pillar", startingLocation: "canals", nadeType: "flash", throwType: "run", side: "T", description: "", map: "overpass", game: "CS2", contentUrl: "https://streamable.com/l/xjvcda/mp4.mp4"},
  { id: "cs2overpass_god_flash_a_site", title: "God flash for A site", startingLocation: "divider", nadeType: "flash", throwType: "jump", side: "T", description: "", map: "overpass", game: "CS2", contentUrl: "https://streamable.com/l/yujl98/mp4.mp4"},
  { id: "cs2overpass_molly_dice_from_divider", title: "Molly dice", startingLocation: "divider", nadeType: "molly", throwType: "jump", side: "T", description: "", map: "overpass", game: "CS2", contentUrl: "https://streamable.com/l/6aztmm/mp4.mp4"},
  { id: "cs2overpass_molly_divider_from_fountain", title: "Molly divider", startingLocation: "fountain", nadeType: "molly", throwType: "walk", side: "T", description: "", map: "overpass", game: "CS2", contentUrl: "https://streamable.com/l/ix5lm4/mp4.mp4"},
  { id: "cs2overpass_molly_party_from_playground", title: "Molly party", startingLocation: "divider", nadeType: "molly", throwType: "walk+jump", side: "T", description: "", map: "overpass", game: "CS2", contentUrl: "https://streamable.com/l/qy7rb7/mp4.mp4"},
  { id: "cs2overpass_molly_pipe", title: "Molly pipe", startingLocation: "jungle", nadeType: "molly", throwType: "normal", side: "T", description: "", map: "overpass", game: "CS2", contentUrl: "https://streamable.com/l/jnuktk/mp4.mp4"},
  { id: "cs2overpass_molly_short_from_t_spawn", title: "Molly short", startingLocation: "T spawn", nadeType: "molly", throwType: "medium, run+jump", side: "T", description: "", map: "overpass", game: "CS2", contentUrl: "https://streamable.com/l/hzrvrh/mp4.mp4"},
  { id: "cs2overpass_molly_short_from_t_spawn_easy", title: "Molly short", startingLocation: "T spawn", nadeType: "molly", throwType: "jump", side: "T", description: "", map: "overpass", game: "CS2", contentUrl: "https://streamable.com/l/uojpqe/mp4.mp4"},
  { id: "cs2overpass_molly_toxic_from_canals", title: "Molly toxic", startingLocation: "canals", nadeType: "molly", throwType: "run+jump", side: "T", description: "", map: "overpass", game: "CS2", contentUrl: "https://streamable.com/l/uafgf6/mp4.mp4"},
  { id: "cs2overpass_molly_truck_from_divider", title: "Molly truck", startingLocation: "divider", nadeType: "molly", throwType: "jump", side: "T", description: "", map: "overpass", game: "CS2", contentUrl: "https://streamable.com/l/z1hi3b/mp4.mp4"},
  { id: "cs2overpass_molly_truck_from_long", title: "Molly truck", startingLocation: "long", nadeType: "molly", throwType: "walk+jump", side: "T", description: "", map: "overpass", game: "CS2", contentUrl: "https://streamable.com/l/5edx5m/mp4.mp4"},
  { id: "cs2overpass_smoke_bank_from_mid", title: "Smoke bank", startingLocation: "mid", nadeType: "smoke", throwType: "jump", side: "T", description: "", map: "overpass", game: "CS2", contentUrl: "https://streamable.com/l/8t53g0/mp4.mp4"},
  { id: "cs2overpass_smoke_bathrooms_from_fountain", title: "Smoke bathrooms", startingLocation: "fountain", nadeType: "smoke", throwType: "run", side: "T", description: "", map: "overpass", game: "CS2", contentUrl: "https://streamable.com/l/n7wprj/mp4.mp4"},
  { id: "cs2overpass_smoke_bathrooms_from_spawn", title: "Smoke bathrooms", startingLocation: "T spawn", nadeType: "smoke", throwType: "jump", side: "T", description: "", map: "overpass", game: "CS2", contentUrl: "https://streamable.com/l/lhushf/mp4.mp4"},
  { id: "cs2overpass_smoke_b_site", title: "Smoke B site", startingLocation: "canals", nadeType: "smoke", throwType: "normal", side: "T", description: "", map: "overpass", game: "CS2", contentUrl: "https://streamable.com/l/anpa3t/mp4.mp4"},
  { id: "cs2overpass_smoke_connector_door_from_t_spawn", title: "Smoke connector door", startingLocation: "T spawn", nadeType: "smoke", throwType: "jump", side: "T", description: "", map: "overpass", game: "CS2", contentUrl: "https://streamable.com/l/kphj1v/mp4.mp4"},
  { id: "cs2overpass_smoke_heaven_from_t_spawn", title: "Smoke heaven", startingLocation: "T spawn", nadeType: "smoke", throwType: "run+jump", side: "T", description: "", map: "overpass", game: "CS2", contentUrl: "https://streamable.com/l/jhoz14/mp4.mp4"},
  { id: "cs2overpass_smoke_heaven_from_water", title: "Smoke heaven", startingLocation: "water", nadeType: "smoke", throwType: "normal", side: "T", description: "", map: "overpass", game: "CS2", contentUrl: "https://streamable.com/l/jti7gl/mp4.mp4"},
  { id: "cs2overpass_smoke_stairs_from_divider", title: "Smoke stairs", startingLocation: "divider", nadeType: "smoke", throwType: "jump", side: "T", description: "", map: "overpass", game: "CS2", contentUrl: "https://streamable.com/l/sn73yq/mp4.mp4"},
  { id: "cs2overpass_smoke_stairs_from_long", title: "Smoke stairs", startingLocation: "long", nadeType: "smoke", throwType: "jump", side: "T", description: "", map: "overpass", game: "CS2", contentUrl: "https://streamable.com/l/i8otcn/mp4.mp4"},
  { id: "cs2overpass_smoke_stairs_from_mid", title: "Smoke stairs", startingLocation: "mid", nadeType: "smoke", throwType: "normal", side: "T", description: "", map: "overpass", game: "CS2", contentUrl: "https://streamable.com/l/cezq4f/mp4.mp4"},
  { id: "cs2overpass_smoke_stairs_from_top_con", title: "Smoke stairs", startingLocation: "top con", nadeType: "smoke", throwType: "jump", side: "T", description: "", map: "overpass", game: "CS2", contentUrl: "https://streamable.com/l/s87qm5/mp4.mp4"},
  { id: "cs2overpass_tooth_flash", title: "Tooth flash", startingLocation: "canals", nadeType: "flash", throwType: "normal", side: "T", description: "", map: "overpass", game: "CS2", contentUrl: "https://streamable.com/l/9a3xvs/mp4.mp4"},
  { id: "cs2overpass_astralis_water_retake_nades", title: "Astralis retake nades", startingLocation: "graffiti", nadeType: "molly, flash", throwType: "jump, normal", side: "CT", description: "", map: "overpass", game: "CS2", contentUrl: "https://streamable.com/l/zogxsk/mp4.mp4"},
  { id: "cs2overpass_defensive_pillar_smoke", title: "Defensive pillar smoke", startingLocation: "pit", nadeType: "smoke", throwType: "normal", side: "CT", description: "", map: "overpass", game: "CS2", contentUrl: "https://streamable.com/l/rvo9k8/mp4.mp4"},
  { id: "cs2overpass_defensive_pillar_smoke_alternate", title: "Defensive pillar smoke (alternate lineup)", startingLocation: "pit", nadeType: "smoke", throwType: "normal", side: "CT", description: "", map: "overpass", game: "CS2", contentUrl: "https://streamable.com/l/kxp7i6/mp4.mp4"},
  { id: "cs2overpass_flash_pipe_from_site", title: "Support flash pipe", startingLocation: "B site", nadeType: "flash", throwType: "normal", side: "CT", description: "", map: "overpass", game: "CS2", contentUrl: "https://streamable.com/l/bvho9v/mp4.mp4"},
  { id: "cs2overpass_molly_a_ramp_start_of_round", title: "Molly A ramp", startingLocation: "mid", nadeType: "molly", throwType: "run+jump", side: "CT", description: "", map: "overpass", game: "CS2", contentUrl: "https://streamable.com/l/4a2b31/mp4.mp4"},
  { id: "cs2overpass_molly_playground", title: "Molly playground", startingLocation: "divider", nadeType: "molly", throwType: "run+jump", side: "CT", description: "", map: "overpass", game: "CS2", contentUrl: "https://streamable.com/l/qgbyq6/mp4.mp4"},
  { id: "cs2overpass_nade_connector_door", title: "Nade connector door", startingLocation: "lower B", nadeType: "he", throwType: "normal", side: "CT", description: "", map: "overpass", game: "CS2", contentUrl: "https://streamable.com/l/f8ncf4/mp4.mp4"},
  { id: "cs2overpass_self_popflash_monster", title: "Self popflash monster", startingLocation: "monster", nadeType: "flash", throwType: "normal", side: "CT", description: "", map: "overpass", game: "CS2", contentUrl: "https://streamable.com/l/is29z8/mp4.mp4"},
  { id: "cs2overpass_smoke_mid_stairs", title: "Smoke mid stairs", startingLocation: "bathrooms", nadeType: "smoke", throwType: "run", side: "CT", description: "", map: "overpass", game: "CS2", contentUrl: "https://streamable.com/l/oit047/mp4.mp4"},
  { id: "cs2overpass_smoke_monster_from_b", title: "Smoke monster", startingLocation: "B site", nadeType: "smoke", throwType: "normal", side: "CT", description: "", map: "overpass", game: "CS2", contentUrl: "https://streamable.com/l/6da4io/mp4.mp4"},
  { id: "cs2overpass_smoke_monster_from_ct_spawn", title: "Smoke monster", startingLocation: "CT spawn", nadeType: "smoke", throwType: "crouch+jump", side: "CT", description: "", map: "overpass", game: "CS2", contentUrl: "https://streamable.com/l/j6kj3w/mp4.mp4"},
  { id: "cs2overpass_support_flash_connector_from_lower", title: "Flash connector", startingLocation: "graffiti", nadeType: "flash", throwType: "normal", side: "CT", description: "", map: "overpass", game: "CS2", contentUrl: "https://streamable.com/l/xm0tqd/mp4.mp4"},
  { id: "cs2overpass_support_flash_monster_from_heaven_easy", title: "Flash monsnter", startingLocation: "heaven", nadeType: "flash", throwType: "normal", side: "CT", description: "", map: "overpass", game: "CS2", contentUrl: "https://streamable.com/l/9cfjia/mp4.mp4"},
  { id: "cs2overpass_support_flash_monster_from_pit", title: "Flash monster", startingLocation: "pit", nadeType: "flash", throwType: "medium", side: "CT", description: "", map: "overpass", game: "CS2", contentUrl: "https://streamable.com/l/v2mtl6/mp4.mp4"},
  { id: "cs2overpass_support_flash_monster_from_site", title: "Support flash monster", startingLocation: "B site", nadeType: "flash", throwType: "normal", side: "CT", description: "", map: "overpass", game: "CS2", contentUrl: "https://streamable.com/l/gg1p48/mp4.mp4"},
  { id: "cs2overpass_support_flash_ramp_for_party_from_divider", title: "Flash ramp for party", startingLocation: "divider", nadeType: "flash", throwType: "jump", side: "CT", description: "", map: "overpass", game: "CS2", contentUrl: "https://streamable.com/l/c8317e/mp4.mp4"},

  // ********************************************** CS2 MIRAGE **********************************************

  // check the instant mirage smoke throw types
  { id: "cs2mirage_instant_window_smoke_spawn1", title: "Instant window smoke (spawn 1)", startingLocation: "T spawn", nadeType: "smoke", throwType: "walk+jump", side: "T", description: "", map: "mirage", game: "CS2", contentUrl: "https://streamable.com/l/s556t0/mp4.mp4"},
  { id: "cs2mirage_instant_window_smoke_spawn2", title: "Instant window smoke (spawn 2)", startingLocation: "T spawn", nadeType: "smoke", throwType: "walk+jump", side: "T", description: "", map: "mirage", game: "CS2", contentUrl: "https://streamable.com/l/cckv9q/mp4.mp4"},
  { id: "cs2mirage_instant_window_smoke_spawn3", title: "Instant window smoke (spawn 3)", startingLocation: "T spawn", nadeType: "smoke", throwType: "crouch+walk+jump", side: "T", description: "", map: "mirage", game: "CS2", contentUrl: "https://streamable.com/l/gb5x78/mp4.mp4"},
  { id: "cs2mirage_instant_window_smoke_spawn4", title: "Instant window smoke (spawn 4)", startingLocation: "T spawn", nadeType: "smoke", throwType: "walk+jump", side: "T", description: "", map: "mirage", game: "CS2", contentUrl: "https://streamable.com/l/pq1b7s/mp4.mp4"},
  { id: "cs2mirage_instant_window_smoke_spawn5", title: "Instant window smoke (spawn 5)", startingLocation: "T spawn", nadeType: "smoke", throwType: "walk+jump", side: "T", description: "", map: "mirage", game: "CS2", contentUrl: "https://streamable.com/l/9m9vt7/mp4.mp4"},
  { id: "cs2mirage_instant_window_smoke_spawn6", title: "Instant window smoke (spawn 6)", startingLocation: "T spawn", nadeType: "smoke", throwType: "jump", side: "T", description: "", map: "mirage", game: "CS2", contentUrl: "https://streamable.com/l/z27bo4/mp4.mp4"},
  { id: "cs2mirage_instant_window_smoke_spawn7", title: "Instant window smoke (spawn 7)", startingLocation: "T spawn", nadeType: "smoke", throwType: "jump", side: "T", description: "", map: "mirage", game: "CS2", contentUrl: "https://streamable.com/l/5rx2s3/mp4.mp4"},
  { id: "cs2mirage_instant_window_smoke_spawn8", title: "Instant window smoke (spawn 8)", startingLocation: "T spawn", nadeType: "smoke", throwType: "walk+jump", side: "T", description: "", map: "mirage", game: "CS2", contentUrl: "https://streamable.com/l/pb9jl7/mp4.mp4"},
  { id: "cs2mirage_instant_window_smoke_spawn9", title: "Instant window smoke (spawn 9)", startingLocation: "T spawn", nadeType: "smoke", throwType: "walk+jump", side: "T", description: "", map: "mirage", game: "CS2", contentUrl: "https://streamable.com/l/9bpt54/mp4.mp4"},
  { id: "cs2mirage_running_smoke_window", title: "Smoke mid window (running lineup)", startingLocation: "T spawn", nadeType: "smoke", throwType: "run+jump", side: "T", description: "", map: "mirage", game: "CS2", contentUrl: "https://streamable.com/l/qkb6g5/mp4.mp4"},
  { id: "cs2mirage_smoke_arch_from_back_apts", title: "Smoke arch", startingLocation: "back apts", nadeType: "smoke", throwType: "normal", side: "T", description: "", map: "mirage", game: "CS2", contentUrl: "https://streamable.com/l/21rb5e/mp4.mp4"},
  { id: "cs2mirage_smoke_back_apts_from_ct_spawn", title: "Smoke back apts", startingLocation: "CT spawn", nadeType: "smoke", throwType: "jump", side: "CT", description: "", map: "mirage", game: "CS2", contentUrl: "https://streamable.com/l/y2mmcx/mp4.mp4"},
  { id: "cs2mirage_smoke_catwalk_from_t_spawn", title: "Smoke catwalk", startingLocation: "T spawn", nadeType: "smoke", throwType: "jump", side: "T", description: "", map: "mirage", game: "CS2", contentUrl: "https://streamable.com/l/3jdvc5/mp4.mp4"},
  { id: "cs2mirage_smoke_connector_from_spawn", title: "Smoke connector", startingLocation: "T spawn", nadeType: "smoke", throwType: "jump", side: "T", description: "", map: "mirage", game: "CS2", contentUrl: "https://streamable.com/l/nsrrq5/mp4.mp4"},
  { id: "cs2mirage_smoke_ct", title: "Smoke CT", startingLocation: "CT spawn", nadeType: "smoke", throwType: "jump", side: "T", description: "", map: "mirage", game: "CS2", contentUrl: "https://streamable.com/l/phvzma/mp4.mp4"},
  { id: "cs2mirage_smoke_jungle_con", title: "Smoke jungle/con", startingLocation: "CT spawn", nadeType: "smoke", throwType: "normal", side: "T", description: "", map: "mirage", game: "CS2", contentUrl: "https://streamable.com/l/prgwjk/mp4.mp4"},
  { id: "cs2mirage_smoke_left_arch_from_back_apts", title: "Smoke left arch", startingLocation: "back apts", nadeType: "smoke", throwType: "normal", side: "T", description: "", map: "mirage", game: "CS2", contentUrl: "https://streamable.com/l/txnad7/mp4.mp4"},
  // { id: "cs2mirage_smoke_market_door_from_back_apts", title: "Smoke market door", startingLocation: "back apts", nadeType: "smoke", throwType: "jump", side: "T", description: "", map: "mirage", game: "CS2", contentUrl: "https://streamable.com/l/xp8p5c/mp4.mp4"},
  { id: "cs2mirage_smoke_market_window_from_back_apts", title: "Smoke market door", startingLocation: "back apts", nadeType: "smoke", throwType: "jump", side: "T", description: "", map: "mirage", game: "CS2", contentUrl: "https://streamable.com/l/hdaszj/mp4.mp4"},
  { id: "cs2mirage_smoke_right_arch_from_back_apts", title: "Smoke right arch", startingLocation: "back apts", nadeType: "smoke", throwType: "jump", side: "T", description: "", map: "mirage", game: "CS2", contentUrl: "https://streamable.com/l/fztrsl/mp4.mp4"},
  { id: "cs2mirage_smoke_stairs", title: "Smoke stairs", startingLocation: "CT spawn", nadeType: "smoke", throwType: "normal", side: "T", description: "", map: "mirage", game: "CS2", contentUrl: "https://streamable.com/l/3xip3v/mp4.mp4"},
  { id: "cs2mirage_standard_window_smoke", title: "Standard window smoke", startingLocation: "CT spawn", nadeType: "smoke", throwType: "hold right", side: "T", description: "", map: "mirage", game: "CS2", contentUrl: "https://streamable.com/l/q2qfmp/mp4.mp4"},
  // this needs to be trimmed above

  // ********************************************** CS2 ANCIENT **********************************************

  { id: "cs2ancient_smoke_temple_from_t_spawn", title: "Smoke temple", startingLocation: "T spawn", nadeType: "smoke", throwType: "jump", side: "T", description: "", map: "ancient", game: "CS2", contentUrl: "https://streamable.com/l/bwe3x1/mp4.mp4"},

  // { id: "cs2overpass_b_site_god_flash", title: "XXXXXXX", startingLocation: "XXXXXX", nadeType: "XXXXX", throwType: "XXXXXX", side: "T", description: "", map: "overpass", game: "CS2", contentUrl: "XXXXXX"},

]   