import { Grenade } from "./grenade";

// TODO: remove comments, remove duplicates, check all files. change hosting for gifs?

export const GRENADES: Grenade[] = [
    // *********************************************** OVERPASS ***********************************************

    { id: "overpass_a_execute_combo_from_short", title: "A execute nades", startingLocation: "divider", nadeType: "smoke, molly, flash", 
    throwType: "normal, jump", description: "Use this to execute A.", map: "overpass", contentUrl: "https://streamable.com/l/w4z08t/mp4.mp4"},
    { id: "overpass_smoke_bank_from_outside_connector", title: "Smoke bank", startingLocation: "outside connector", nadeType: "smoke", 
    throwType: "jump", description: "", map: "overpass", contentUrl: "https://streamable.com/l/3e0k0p/mp4.mp4"},
    { id: "overpass_anti_eco_a_utility", title: "Anti-eco utility for A", startingLocation: "CT spawn", nadeType: "molly, flash", 
    throwType: "normal, jump", description: "", map: "overpass", contentUrl: "https://streamable.com/l/jskaxw/mp4.mp4"},
    { id: "overpass_molly_toxic_for_real", title: "Molly toxic", startingLocation: "canals", nadeType: "molly", 
    throwType: "forward jump", description: "This is a forward+jump throw.", map: "overpass", contentUrl: "https://streamable.com/l/177ygl/mp4.mp4"},
    // starting here
    { id: "overpass_support_flash_monster", title: "Support flash monster", startingLocation: "heaven", nadeType: "flash", 
    throwType: "run", description: "", map: "overpass", contentUrl: "https://streamable.com/l/48i8fc/mp4.mp4"},
    { id: "overpass_support_flash_b_from_a", title: "Support flash B", startingLocation: "CT spawn", nadeType: "flash", 
    throwType: "run", description: "", map: "overpass", contentUrl: "https://streamable.com/l/m1rer5/mp4.mp4"},
    { id: "overpass_support_flash_over_monster", title: "Support flash over monster", startingLocation: "canals", nadeType: "flash", 
    throwType: "normal", description: "", map: "overpass", contentUrl: "https://streamable.com/l/t6u3i5/mp4.mp4"},
    // { id: "overpass_standard_b_setup_person2", title: "XXXXX", startingLocation: "XXXXXX", nadeType: "XXXXXXX", 
    // throwType: "XXXXX", description: "", map: "XXXXX", contentUrl: "XXXXXXX"},
    // { id: "overpass_standard_b_setup_person3", title: "XXXXX", startingLocation: "XXXXXX", nadeType: "XXXXXXX", 
    // throwType: "XXXXX", description: "", map: "XXXXX", contentUrl: "XXXXXXX"},
    { id: "overpass_support_flash_mid", title: "Support flash mid", startingLocation: "outside bathrooms", nadeType: "flash", 
    throwType: "normal", description: "", map: "overpass", contentUrl: "https://streamable.com/l/1nhpgl/mp4.mp4"},
    // { id: "overpass_standard_b_setup_person1", title: "XXXXX", startingLocation: "XXXXXX", nadeType: "XXXXXXX", 
    // throwType: "XXXXX", description: "", map: "XXXXX", contentUrl: "XXXXXXX"},
    { id: "overpass_support_flash_deep_monster", title: "Support flash deep monster", startingLocation: "headshot", nadeType: "flash", 
    throwType: "jump", description: "", map: "overpass", contentUrl: "https://streamable.com/l/fsyd7d/mp4.mp4"},
    { id: "overpass_wallbang_door", title: "Wallbang connector door", startingLocation: "lower", nadeType: "wallbang", 
    throwType: "none", description: "", map: "overpass", contentUrl: "https://streamable.com/l/7th7pc/mp4.mp4"},
    { id: "overpass_smoke_stairs_from_long", title: "Smoke stairs", startingLocation: "long", nadeType: "smoke", 
    throwType: "run", description: "", map: "overpass", contentUrl: "https://streamable.com/l/bkqedp/mp4.mp4"},
    { id: "overpass_smoke_left_pillar", title: "Smoke left pillar", startingLocation: "below heaven", nadeType: "smoke", 
    throwType: "normal", description: "", map: "overpass", contentUrl: "https://streamable.com/l/904sqz/mp4.mp4"},
    { id: "overpass_smoke_stairs_from_short", title: "Smoke stairs", startingLocation: "divider", nadeType: "smoke", 
    throwType: "normal", description: "", map: "overpass", contentUrl: "https://streamable.com/l/z5lmf1/mp4.mp4"},
    { id: "overpass_smoke_heaven_from_site", title: "Smoke heaven", startingLocation: "B site", nadeType: "smoke", 
    throwType: "normal", description: "", map: "overpass", contentUrl: "https://streamable.com/l/xkgtb2/mp4.mp4"},
    { id: "overpass_smoke_monster_from_lower", title: "Smoke monster", startingLocation: "lower", nadeType: "smoke", 
    throwType: "normal", description: "", map: "overpass", contentUrl: "https://streamable.com/l/hu7e6c/mp4.mp4"},
    { id: "overpass_smoke_water_from_spawn", title: "Smoke water", startingLocation: "CT spawn", nadeType: "smoke", 
    throwType: "normal", description: "", map: "overpass", contentUrl: "https://streamable.com/l/xg8d1y/mp4.mp4"},
    { id: "overpass_solo_lurk_b", title: "Solo lurk B nades", startingLocation: "canals", nadeType: "molly, flash", 
    throwType: "jump, run", description: "", map: "overpass", contentUrl: "https://streamable.com/l/gc34hm/mp4.mp4"},
    { id: "overpass_smoke_heaven_from_water", title: "Smoke heaven", startingLocation: "outside pipe", nadeType: "smoke", 
    throwType: "jump", description: "", map: "overpass", contentUrl: "https://streamable.com/l/v8nvr2/mp4.mp4"},
    { id: "overpass_solo_connector_utility_set", title: "Solo connector utility", startingLocation: "connector", nadeType: "molly, flash, he", 
    throwType: "normal, run", description: "", map: "overpass", contentUrl: "https://streamable.com/l/mo18xx/mp4.mp4"},
    { id: "overpass_smoke_long_lurk", title: "Long lurk smoke", startingLocation: "long", nadeType: "smoke", 
    throwType: "normal", description: "", map: "overpass", contentUrl: "https://streamable.com/l/4vzd2c/mp4.mp4"},
    { id: "overpass_smoke_heaven_from_t_spawn", title: "Smoke heaven", startingLocation: "T spawn", nadeType: "smoke", 
    throwType: "run+jump", description: "", map: "overpass", contentUrl: "https://streamable.com/l/bw75a7/mp4.mp4"},
    { id: "overpass_smoke_mid", title: "Smoke mid", startingLocation: "bathrooms", nadeType: "smoke", 
    throwType: "run", description: "", map: "overpass", contentUrl: "https://streamable.com/l/09j81w/mp4.mp4"},
    { id: "overpass_smoke_monster_from_ct_spawn", title: "Smoke monster", startingLocation: "CT spawn", nadeType: "smoke", 
    throwType: "jump", description: "", map: "overpass", contentUrl: "https://streamable.com/l/1vq52f/mp4.mp4"},
    { id: "overpass_smoke_monster_from_truck", title: "Smoke monster", startingLocation: "truck", nadeType: "smoke", 
    throwType: "normal", description: "", map: "overpass", contentUrl: "https://streamable.com/l/9yywhh/mp4.mp4"},
    { id: "overpass_smoke_heaven_from_short_pipe", title: "Smoke heaven", startingLocation: "outside pipe", nadeType: "smoke", 
    throwType: "walk", description: "", map: "overpass", contentUrl: "https://streamable.com/l/ufkd52/mp4.mp4"},
    { id: "overpass_smoke_bathrooms_from_party", title: "Smoke bathrooms", startingLocation: "playground", nadeType: "smoke", 
    throwType: "normal", description: "", map: "overpass", contentUrl: "https://streamable.com/l/0s64s5/mp4.mp4"},
    { id: "overpass_smoke_bridge", title: "Smoke bridge", startingLocation: "water", nadeType: "smoke", 
    throwType: "normal", description: "", map: "overpass", contentUrl: "https://streamable.com/l/884max/mp4.mp4"},
    { id: "overpass_smoke_bathrooms_from_t_spawn", title: "Smoke bathrooms", startingLocation: "T spawn", nadeType: "smoke", 
    throwType: "jump", description: "", map: "overpass", contentUrl: "https://streamable.com/l/p5ocwc/mp4.mp4"},
    { id: "overpass_smoke_bathrooms_from_playground", title: "Smoke bathrooms", startingLocation: "playground", nadeType: "smoke", 
    throwType: "normal", description: "", map: "overpass", contentUrl: "https://streamable.com/l/pxspp2/mp4.mp4"},
    { id: "overpass_smoke_heaven_from_connector", title: "Smoke heaven", startingLocation: "connector", nadeType: "smoke", 
    throwType: "normal", description: "", map: "overpass", contentUrl: "https://streamable.com/l/cml9bq/mp4.mp4"},
    { id: "overpass_smoke_easy_long_lurk", title: "Easy long lurk smoke", startingLocation: "long", nadeType: "smoke", 
    throwType: "jump", description: "", map: "overpass", contentUrl: "https://streamable.com/l/joorkl/mp4.mp4"},
    { id: "overpass_smoke_bathroom_from_outside_party", title: "Smoke bathrooms", startingLocation: "outside party", nadeType: "smoke", 
    throwType: "run", description: "", map: "overpass", contentUrl: "https://streamable.com/l/s9fskw/mp4.mp4"},
    { id: "overpass_smoke_bridge_from_water", title: "Smoke bridge", startingLocation: "water", nadeType: "smoke", 
    throwType: "normal", description: "", map: "overpass", contentUrl: "https://streamable.com/l/sy5mtp/mp4.mp4"},
    { id: "overpass_smoke_bank_from_long", title: "Smoke bank", startingLocation: "long", nadeType: "smoke", 
    throwType: "normal", description: "", map: "overpass", contentUrl: "https://streamable.com/l/8pjhbf/mp4.mp4"},
    { id: "overpass_smoke_divider_from_t_spawn", title: "Smoke divier", startingLocation: "T spawn", nadeType: "smoke", 
    throwType: "jump", description: "", map: "overpass", contentUrl: "https://streamable.com/l/iximn6/mp4.mp4"},
    { id: "overpass_smoke_heaven", title: "Smoke heaven", startingLocation: "water", nadeType: "smoke", 
    throwType: "normal", description: "", map: "overpass", contentUrl: "https://streamable.com/l/32afbx/mp4.mp4"},
    { id: "overpass_popflash_retake_from_monster", title: "A retake flash", startingLocation: "outside monster?", nadeType: "flash", //change this
    throwType: "jump", description: "", map: "overpass", contentUrl: "https://streamable.com/l/ji3ln0/mp4.mp4"},
    { id: "overpass_popflash_long_1", title: "Popflash long 1", startingLocation: "long?", nadeType: "flash", //change
    throwType: "normal", description: "", map: "overpass", contentUrl: "https://streamable.com/l/p5vvv8/mp4.mp4"},
    // { id: "overpass_run_boost_setup_b_person1", title: "XXXXX", startingLocation: "XXXXXX", nadeType: "XXXXXXX", 
    // throwType: "XXXXX", description: "", map: "XXXXX", contentUrl: "XXXXXXX"},
    { id: "overpass_popflash_water_solo_start_of_round", title: "Popflash water (solo)", startingLocation: "water", nadeType: "flash", 
    throwType: "run", description: "", map: "overpass", contentUrl: "https://streamable.com/l/ae4hsy/mp4.mp4"},
    { id: "overpass_popflash_long_2", title: "Popflash long 2", startingLocation: "long?", nadeType: "flash", //change
    throwType: "normal", description: "", map: "overpass", contentUrl: "https://streamable.com/l/gqg7y8/mp4.mp4"},
    { id: "overpass_popflash_monster_from_back_site", title: "Popflash monster", startingLocation: "back B site", nadeType: "flash", 
    throwType: "normal", description: "", map: "overpass", contentUrl: "https://streamable.com/l/n1pinx/mp4.mp4"},
    { id: "overpass_popflash_through_pipe_smoke", title: "Popflash through smoke", startingLocation: "water", nadeType: "flash", 
    throwType: "right click", description: "", map: "overpass", contentUrl: "https://streamable.com/l/xshums/mp4.mp4"},
    // { id: "overpass_run_boost_setup_b_person2", title: "XXXXX", startingLocation: "XXXXXX", nadeType: "XXXXXXX", 
    // throwType: "XXXXX", description: "", map: "XXXXX", contentUrl: "XXXXXXX"},
    { id: "overpass_popflash_pipe", title: "Popflash pipe", startingLocation: "B short", nadeType: "flash", 
    throwType: "run, right click", description: "", map: "overpass", contentUrl: "https://streamable.com/l/e9eqgd/mp4.mp4"},
    { id: "overpass_popflash_front_bathrooms_from_truck", title: "Popflash front bathrooms", startingLocation: "truck", nadeType: "flash", 
    throwType: "normal", description: "", map: "overpass", contentUrl: "https://streamable.com/l/2tb2cc/mp4.mp4"},
    // { id: "overpass_oneway_t_water", title: "XXXXX", startingLocation: "XXXXXX", nadeType: "XXXXXXX", 
    // throwType: "XXXXX", description: "", map: "XXXXX", contentUrl: "XXXXXXX"},
    // { id: "overpass_oneway_ct_heaven", title: "XXXXX", startingLocation: "XXXXXX", nadeType: "XXXXXXX", 
    // throwType: "XXXXX", description: "", map: "XXXXX", contentUrl: "XXXXXXX"},
    // { id: "overpass_oneway_t_connector", title: "XXXXX", startingLocation: "XXXXXX", nadeType: "XXXXXXX", 
    // throwType: "XXXXX", description: "", map: "XXXXX", contentUrl: "XXXXXXX"},
    { id: "overpass_nade_monster_ct", title: "Nade monster", startingLocation: "lower", nadeType: "he", 
    throwType: "normal", description: "", map: "overpass", contentUrl: "https://streamable.com/l/mmxco7/mp4.mp4"},
    // { id: "overpass_oneway_ct_connector", title: "XXXXX", startingLocation: "XXXXXX", nadeType: "XXXXXXX", 
    // throwType: "XXXXX", description: "", map: "XXXXX", contentUrl: "XXXXXXX"},
    // { id: "overpass_oneway_ct_bathrooms", title: "XXXXX", startingLocation: "XXXXXX", nadeType: "XXXXXXX", 
    // throwType: "XXXXX", description: "", map: "XXXXX", contentUrl: "XXXXXXX"},
    { id: "overpass_nade_playground_from_bathrooms", title: "Nade playground", startingLocation: "bathrooms", nadeType: "he", 
    throwType: "run+jump", description: "", map: "overpass", contentUrl: "https://streamable.com/l/f43w0w/mp4.mp4"},
    { id: "overpass_nade_door", title: "Nade connector door", startingLocation: "lower", nadeType: "he", 
    throwType: "normal", description: "", map: "overpass", contentUrl: "https://streamable.com/l/o6674s/mp4.mp4"},
    { id: "overpass_nade_connector_door_easy", title: "Nade connector door (easy)", startingLocation: "lower", nadeType: "he", 
    throwType: "normal", description: "", map: "overpass", contentUrl: "https://streamable.com/l/nbgboj/mp4.mp4"},
    { id: "overpass_molly_headshot", title: "Molly headshot", startingLocation: "water", nadeType: "molly", 
    throwType: "normal", description: "", map: "overpass", contentUrl: "https://streamable.com/l/2fpukn/mp4.mp4"},
    { id: "overpass_molly_short_control", title: "Molly short", startingLocation: "control room", nadeType: "molly", 
    throwType: "normal", description: "", map: "overpass", contentUrl: "https://streamable.com/l/lhvnwx/mp4.mp4"},
    { id: "overpass_molly_dumpster_from_top_connector", title: "Molly dumpster", startingLocation: "top connector", nadeType: "molly", 
    throwType: "run+jump", description: "", map: "overpass", contentUrl: "https://streamable.com/l/0u9k51/mp4.mp4"},
    { id: "overpass_molly_toxic_from_back_water", title: "Molly toxic", startingLocation: "back water", nadeType: "molly", 
    throwType: "quick run", description: "", map: "overpass", contentUrl: "https://streamable.com/l/4e52cf/mp4.mp4"},
    { id: "overpass_molly_lower_from_monster", title: "Molly lower", startingLocation: "monster", nadeType: "molly", 
    throwType: "run", description: "", map: "overpass", contentUrl: "https://streamable.com/l/n05el5/mp4.mp4"},
    { id: "overpass_molly_party_from_back_playground", title: "Molly party", startingLocation: "back playground", nadeType: "molly", 
    throwType: "jump", description: "", map: "overpass", contentUrl: "https://streamable.com/l/j2cm3d/mp4.mp4"},
    { id: "overpass_molly_short_quick", title: "Molly short (quick)", startingLocation: "T spawn", nadeType: "molly", 
    throwType: "run", description: "", map: "overpass", contentUrl: "https://streamable.com/l/cfdzzg/mp4.mp4"},
    { id: "overpass_molly_truck_from_long", title: "Molly truck", startingLocation: "long", nadeType: "molly", 
    throwType: "run", description: "", map: "overpass", contentUrl: "https://streamable.com/l/dk4hvb/mp4.mp4"},
    { id: "overpass_molly_truck_from_short", title: "Molly truck", startingLocation: "A short", nadeType: "molly", 
    throwType: "jump", description: "", map: "overpass", contentUrl: "https://streamable.com/l/8z2jah/mp4.mp4"},
    { id: "overpass_molly_barrels_from_water", title: "Molly toxic", startingLocation: "water", nadeType: "molly", 
    throwType: "jump", description: "", map: "overpass", contentUrl: "https://streamable.com/l/knz0et/mp4.mp4"},
    { id: "overpass_molly_deep_playground", title: "Molly deep playground", startingLocation: "divider", nadeType: "molly", 
    throwType: "run+jump", description: "", map: "overpass", contentUrl: "https://streamable.com/l/cip7i4/mp4.mp4"},
    // { id: "overpass_lower_smoke_wall", title: "XXXXX", startingLocation: "XXXXXX", nadeType: "XXXXXXX", 
    // throwType: "XXXXX", description: "", map: "XXXXX", contentUrl: "XXXXXXX"},
    { id: "overpass_lurk_b_smoke", title: "B lurk smoke", startingLocation: "T spawn", nadeType: "smoke", 
    throwType: "normal", description: "", map: "overpass", contentUrl: "https://streamable.com/l/ho8acs/mp4.mp4"},
    { id: "overpass_molly_divider", title: "Molly divider", startingLocation: "fountain", nadeType: "molly", 
    throwType: "quick run", description: "", map: "overpass", contentUrl: "https://streamable.com/l/9rj6vz/mp4.mp4"},
    { id: "overpass_molly_default_a_from_long", title: "Molly dice", startingLocation: "long", nadeType: "molly", 
    throwType: "normal", description: "", map: "overpass", contentUrl: "https://streamable.com/l/d4nas3/mp4.mp4"},
    { id: "overpass_molly_default_a", title: "Molly dice", startingLocation: "divider", nadeType: "molly", 
    throwType: "jump", description: "", map: "overpass", contentUrl: "https://streamable.com/l/jub28n/mp4.mp4"},
    { id: "overpass_molly_deep_connector_from_party", title: "Molly deep connector", startingLocation: "party", nadeType: "molly", 
    throwType: "normal", description: "", map: "overpass", contentUrl: "https://streamable.com/l/6h1bvb/mp4.mp4"},
    // { id: "overpass_long_flashes_for_cafe", title: "XXXXX", startingLocation: "XXXXXX", nadeType: "XXXXXXX", 
    // throwType: "XXXXX", description: "", map: "XXXXX", contentUrl: "XXXXXXX"},
    { id: "overpass_molly_deep_mid", title: "Molly deep mid", startingLocation: "A short", nadeType: "molly", 
    throwType: "run+jump", description: "", map: "overpass", contentUrl: "https://streamable.com/l/qwxn8u/mp4.mp4"},
    { id: "overpass_flash_mid_from_top_long", title: "Flash mid", startingLocation: "top long", nadeType: "flash", 
    throwType: "normal", description: "", map: "overpass", contentUrl: "https://streamable.com/l/pwaoj9/mp4.mp4"},
    { id: "overpass_flash_long_bathrooms", title: "Flash long bathrooms", startingLocation: "long", nadeType: "flash", 
    throwType: "run", description: "", map: "overpass", contentUrl: "https://streamable.com/l/db1wq7/mp4.mp4"},
    { id: "overpass_flash_support_short", title: "Support flash short", startingLocation: "below heaven", nadeType: "flash",
    throwType: "run", description: "", map: "overpass", contentUrl: "https://streamable.com/l/teyfzp/mp4.mp4"},
    { id: "overpass_flash_short_for_rush", title: "Flash short for B rush", startingLocation: "canals", nadeType: "flash",
    throwType: "normal", description: "", map: "overpass", contentUrl: "https://streamable.com/l/yy1222/mp4.mp4"},
    { id: "overpass_flash_party_from_ramp", title: "Flash party", startingLocation: "ramp", nadeType: "flash",
    throwType: "quick run", description: "", map: "overpass", contentUrl: "https://streamable.com/l/wbp1zb/mp4.mp4"},
    { id: "overpass_flash_short_from_connector", title: "Flash short", startingLocation: "connector", nadeType: "flash",
    throwType: "quick run", description: "", map: "overpass", contentUrl: "https://streamable.com/l/dqp91i/mp4.mp4"},
    { id: "overpass_flashes_for_b_execute", title: "Flashes for B execute", startingLocation: "water", nadeType: "flash",
    throwType: "normal", description: "", map: "overpass", contentUrl: "https://streamable.com/l/jukbry/mp4.mp4"},
    { id: "overpass_flash_pop_water", title: "Popflash water", startingLocation: "connector", nadeType: "flash",
    throwType: "normal", description: "", map: "overpass", contentUrl: "https://streamable.com/l/ih99mh/mp4.mp4"},
    { id: "overpass_flash_from_playground", title: "Flash above fountain", startingLocation: "playground", nadeType: "flash",
    throwType: "normal", description: "", map: "overpass", contentUrl: "https://streamable.com/l/v90uxf/mp4.mp4"},
    { id: "overpass_flash_pop_monster_for_t", title: "Nose flash", startingLocation: "canals", nadeType: "flash",
    throwType: "normal", description: "", map: "overpass", contentUrl: "https://streamable.com/l/csmopa/mp4.mp4"},
    { id: "overpass_flash_mid_from_party", title: "Flash mid", startingLocation: "party", nadeType: "flash",
    throwType: "normal", description: "", map: "overpass", contentUrl: "https://streamable.com/l/im84qw/mp4.mp4"},
    { id: "overpass_flash_far_long", title: "Flash long", startingLocation: "playground", nadeType: "flash",
    throwType: "jump", description: "", map: "overpass", contentUrl: "https://streamable.com/l/kzq38s/mp4.mp4"},
    { id: "overpass_flash_front_bathroom_from_party", title: "Flash front bathrooms", startingLocation: "party", nadeType: "flash",
    throwType: "normal", description: "", map: "overpass", contentUrl: "https://streamable.com/l/co9my0/mp4.mp4"},
    { id: "overpass_flash_combo_for_a", title: "Flash combo for A", startingLocation: "A short", nadeType: "flash",
    throwType: "run", description: "", map: "overpass", contentUrl: "https://streamable.com/l/oy0efn/mp4.mp4"},
    { id: "overpass_flash_aggressive_ramp_t", title: "Flash for ramp push", startingLocation: "ramp", nadeType: "flash",
    throwType: "quick run", description: "", map: "overpass", contentUrl: "https://streamable.com/l/xr0gis/mp4.mp4"},
    { id: "overpass_flash_close_long", title: "Flash long", startingLocation: "long", nadeType: "flash",
    throwType: "normal", description: "", map: "overpass", contentUrl: "https://streamable.com/l/vijpvl/mp4.mp4"},
    { id: "overpass_fast_molly_pipe", title: "Molly pipe (fast)", startingLocation: "lower", nadeType: "molly",
    throwType: "run+medium throw", description: "", map: "overpass", contentUrl: "https://streamable.com/l/6r3mp4/mp4.mp4"},
    { id: "overpass_defensive_long_setup", title: "Defense long smoke", startingLocation: "A site", nadeType: "smoke",
    throwType: "quick run", description: "", map: "overpass", contentUrl: "https://streamable.com/l/5knvxy/mp4.mp4"},
    { id: "overpass_defensive_smoke_from_long", title: "Defensive A smoke", startingLocation: "long", nadeType: "smoke",
    throwType: "right click", description: "", map: "overpass", contentUrl: "https://streamable.com/l/43gt0d/mp4.mp4"},
    { id: "overpass_ct_utility_combo_divider", title: "Divider utility", startingLocation: "outside bathrooms", nadeType: "smoke, he",
    throwType: "quick run", description: "", map: "overpass", contentUrl: "https://streamable.com/l/sucwo2/mp4.mp4"},
    // { id: "overpass_aggressive_a_setup_ct_person1", title: "XXXXX", startingLocation: "XXXXXX", nadeType: "XXXXXXX",
    // throwType: "XXXXX", description: "", map: "XXXXX", contentUrl: "XXXXXXX"},
    // { id: "overpass_aggressive_a_setup_ct_person2", title: "XXXXX", startingLocation: "XXXXXX", nadeType: "XXXXXXX",
    // throwType: "XXXXX", description: "", map: "XXXXX", contentUrl: "XXXXXXX"},
    // { id: "overpass_aggressive_a_setup_ct_person3", title: "XXXXX", startingLocation: "XXXXXX", nadeType: "XXXXXXX",
    // throwType: "XXXXX", description: "", map: "XXXXX", contentUrl: "XXXXXXX"},
    { id: "overpass_back_corner_wallbang", title: "Pipe wallbang", startingLocation: "lower", nadeType: "wallbang",
    throwType: "none", description: "", map: "overpass", contentUrl: "https://streamable.com/l/153sm7/mp4.mp4"},
    { id: "overpass_boost_connector_for_pipe", title: "Boost for pipe", startingLocation: "connector", nadeType: "boost",
    throwType: "none", description: "", map: "overpass", contentUrl: "https://streamable.com/l/yfh1n8/mp4.mp4"},

    // *********************************************** NUKE ***********************************************

    { id: "nuke_a_exec_back_silo_molly_and_flashes", title: "Back silo molly and flashes", startingLocation: "T roof", nadeType: "molly, flash",
    throwType: "jump", description: "", map: "nuke", contentUrl: "https://streamable.com/l/bsby8g/mp4.mp4"},
    { id: "nuke_molly_top_hut_and_flashes", title: "Molly top hut and flashes", startingLocation: "T roof", nadeType: "molly, flash",
    throwType: "run+jump", description: "The windows need to be shot out first.", map: "nuke", contentUrl: "https://streamable.com/l/yc34rg/mp4.mp4"},
    // { id: "nuke_molly_top_hut_and_flash", title: "Molly top hut and flash", startingLocation: "T roof", nadeType: "molly, flash",
    // throwType: "run+jump, normal", description: "", map: "nuke", contentUrl: "https://streamable.com/l/u427n0/mp4.mp4"},
    { id: "nuke_smoke_hell_from_outside", title: "Smoke hell", startingLocation: "outside", nadeType: "smoke",
    throwType: "run+jump", description: "", map: "nuke", contentUrl: "https://streamable.com/l/be7nxc/mp4.mp4"},
    { id: "nuke_smoke_mini_from_silo", title: "Smoke mini", startingLocation: "silo", nadeType: "smoke",
    throwType: "run", description: "", map: "nuke", contentUrl: "https://streamable.com/l/grplil/mp4.mp4"},
    { id: "nuke_molly_top_hut_and_flash", title: "Molly top hut and flash", startingLocation: "T roof", nadeType: "molly, flash",
    throwType: "jump", description: "", map: "nuke", contentUrl: "https://streamable.com/l/o91oeu/mp4.mp4"},
    { id: "nuke_vent_rush_utility", title: "Vent rush utility", startingLocation: "lobby", nadeType: "smoke, he",
    throwType: "run, right click", description: "", map: "nuke", contentUrl: "https://streamable.com/l/51w35n/mp4.mp4"},
    { id: "nuke_vent_smoke", title: "Vent smoke and HE", startingLocation: "lobby", nadeType: "smoke, he",
    throwType: "run", description: "", map: "nuke", contentUrl: "https://streamable.com/l/xdilpi/mp4.mp4"},
    { id: "nuke_vent_rush_smoke_from_spawn", title: "Vent rush smoke", startingLocation: "T spawn", nadeType: "smoke",
    throwType: "jump", description: "", map: "nuke", contentUrl: "https://streamable.com/l/3r58sp/mp4.mp4"},
    { id: "nuke_smokewall_from_outside2", title: "Smokewall 2", startingLocation: "outside", nadeType: "smoke",
    throwType: "normal", description: "", map: "nuke", contentUrl: "https://streamable.com/l/a7anr0/mp4.mp4"},
    { id: "nuke_smokewall_from_spawn2", title: "Smokewall 2", startingLocation: "outside", nadeType: "smoke",
    throwType: "jump", description: "", map: "nuke", contentUrl: "https://streamable.com/l/podzn6/mp4.mp4"},
    { id: "nuke_smokewall_from_spawn1", title: "Smokewall 1", startingLocation: "T spawn", nadeType: "smoke",
    throwType: "jump", description: "", map: "nuke", contentUrl: "https://streamable.com/l/oyn39o/mp4.mp4"},
    { id: "nuke_smoke_outside_to_peek_silo", title: "Smoke outside (gla1ve smoke)", startingLocation: "CT spawn", nadeType: "smoke",
    throwType: "run", description: "", map: "nuke", contentUrl: "https://streamable.com/l/bo4ejx/mp4.mp4"},
    { id: "nuke_smoke_a_main_from_outside_closer", title: "Smoke A main", startingLocation: "outside A main", nadeType: "smoke",
    throwType: "run", description: "", map: "nuke", contentUrl: "https://streamable.com/l/rg34yc/mp4.mp4"},
    { id: "nuke_smoke_squeaky_from_heaven", title: "Smoke squeaky", startingLocation: "heaven", nadeType: "smoke",
    throwType: "normal", description: "", map: "nuke", contentUrl: "https://streamable.com/l/t7jkuj/mp4.mp4"},
    { id: "nuke_smokewall_from_outside1", title: "Smokewall 1", startingLocation: "outside", nadeType: "smoke",
    throwType: "normal", description: "", map: "nuke", contentUrl: "https://streamable.com/l/6zz7z9/mp4.mp4"},
    { id: "nuke_smoke_garage", title: "Smoke garage", startingLocation: "outside", nadeType: "smoke",
    throwType: "normal", description: "", map: "nuke", contentUrl: "https://streamable.com/l/lrftb5/mp4.mp4"},
    { id: "nuke_smoke_default", title: "Smoke default", startingLocation: "vending", nadeType: "smoke",
    throwType: "walk", description: "", map: "nuke", contentUrl: "https://streamable.com/l/a71jmu/mp4.mp4"},
    { id: "nuke_smoke_a_main_from_outside", title: "Smoke A main", startingLocation: "outside", nadeType: "smoke",
    throwType: "run", description: "", map: "nuke", contentUrl: "https://streamable.com/l/wih1a2/mp4.mp4"},
    { id: "nuke_smoke_a_main", title: "Smoke A main (and HE)", startingLocation: "lobby", nadeType: "smoke, he",
    throwType: "run", description: "", map: "nuke", contentUrl: "https://streamable.com/l/361awx/mp4.mp4"},
    { id: "nuke_ramp_lamp_flash", title: "Lamp flash", startingLocation: "ramp", nadeType: "flash",
    throwType: "normal", description: "", map: "nuke", contentUrl: "https://streamable.com/l/w8p5ir/mp4.mp4"},
    // { id: "nuke_ramp_oneway_smoke", title: "XXXXX", startingLocation: "XXXXXX", nadeType: "XXXXXXX",
    // throwType: "XXXXX", description: "", map: "XXXXX", contentUrl: "XXXXXXX"},
    { id: "nuke_pop_flash_vent", title: "Popflash vent", startingLocation: "A site", nadeType: "flash",
    throwType: "right click", description: "", map: "nuke", contentUrl: "https://streamable.com/l/jh1nlq/mp4.mp4"},
    // { id: "nuke_secret_oneway_smoke", title: "XXXXX", startingLocation: "XXXXXX", nadeType: "XXXXXXX",
    // throwType: "XXXXX", description: "", map: "XXXXX", contentUrl: "XXXXXXX"},
    { id: "nuke_ramp_anti_rush_utility", title: "Anti-rush utility", startingLocation: "ramp", nadeType: "smoke, he",
    throwType: "run", description: "", map: "nuke", contentUrl: "https://streamable.com/l/jacijo/mp4.mp4"},
    // { id: "nuke_silo_utility_combo", title: "XXXXX", startingLocation: "XXXXXX", nadeType: "XXXXXXX",
    // throwType: "XXXXX", description: "", map: "XXXXX", contentUrl: "XXXXXXX"},
    { id: "nuke_ramp_utility_set_t_side", title: "T side ramp utility", startingLocation: "ramp", nadeType: "smoke, flash",
    throwType: "normal, run", description: "", map: "nuke", contentUrl: "https://streamable.com/l/cf437x/mp4.mp4"},
    { id: "nuke_molly_dark", title: "Molly dark", startingLocation: "below ramp", nadeType: "molly",
    throwType: "normal", description: "", map: "nuke", contentUrl: "https://streamable.com/l/fcyeu2/mp4.mp4"},
    // { id: "nuke_lobby_lurk_smoke_nartouthere", title: "XXXXX", startingLocation: "XXXXXX", nadeType: "XXXXXXX",
    // throwType: "XXXXX", description: "", map: "XXXXX", contentUrl: "XXXXXXX"},
    { id: "nuke_molly_for_ct_hut_rush", title: "Fake hut molly", startingLocation: "heaven", nadeType: "molly",
    throwType: "normal", description: "", map: "nuke", contentUrl: "https://streamable.com/l/qfw07l/mp4.mp4"},
    { id: "nuke_molly_double_doors", title: "Molly double doors", startingLocation: "below ramp", nadeType: "molly",
    throwType: "quick run", description: "", map: "nuke", contentUrl: "https://streamable.com/l/4kls5n/mp4.mp4"},
    { id: "nuke_molly_behind_blue_box_two_ways", title: "Molly behind blue box", startingLocation: "top mini", nadeType: "molly",
    throwType: "run", description: "", map: "nuke", contentUrl: "https://streamable.com/l/f4ei5v/mp4.mp4"},
    { id: "nuke_molly_secret_from_outside", title: "Molly secret", startingLocation: "outside", nadeType: "molly",
    throwType: "normal", description: "", map: "nuke", contentUrl: "https://streamable.com/l/rutfhq/mp4.mp4"},
    { id: "nuke_mini_smoke_utility_combo_from_top_mini", title: "Top mini utility", startingLocation: "top mini", nadeType: "smoke, molly, flash",
    throwType: "normal, run", description: "", map: "nuke", contentUrl: "https://streamable.com/l/7qm2bt/mp4.mp4"},
    { id: "nuke_molly_squeaky_from_heaven", title: "Molly squeaky", startingLocation: "heaven", nadeType: "molly",
    throwType: "run", description: "", map: "nuke", contentUrl: "https://streamable.com/l/tkkzmi/mp4.mp4"},
    { id: "nuke_molly_outside_prevent_rush", title: "Molly outside anti-rush", startingLocation: "CT spawn", nadeType: "molly",
    throwType: "walk+jump", description: "", map: "nuke", contentUrl: "https://streamable.com/l/f9cw0i/mp4.mp4"},
    { id: "nuke_molly_silo", title: "Molly silo", startingLocation: "blue box", nadeType: "molly",
    throwType: "jump", description: "", map: "nuke", contentUrl: "https://streamable.com/l/k9lge2/mp4.mp4"},
    // { id: "nuke_molly_hut_from_t_roof", title: "XXXXX", startingLocation: "XXXXXX", nadeType: "XXXXXXX",
    // throwType: "XXXXX", description: "", map: "XXXXX", contentUrl: "XXXXXXX"},
    // { id: "nuke_hut_rush_setup_person1", title: "XXXXX", startingLocation: "XXXXXX", nadeType: "XXXXXXX",
    // throwType: "XXXXX", description: "", map: "XXXXX", contentUrl: "XXXXXXX"},
    // { id: "nuke_hut_rush_setup_person2", title: "XXXXX", startingLocation: "XXXXXX", nadeType: "XXXXXXX",
    // throwType: "XXXXX", description: "", map: "XXXXX", contentUrl: "XXXXXXX"},
    // { id: "nuke_hut_rush_setup_person3", title: "XXXXX", startingLocation: "XXXXXX", nadeType: "XXXXXXX",
    // throwType: "XXXXX", description: "", map: "XXXXX", contentUrl: "XXXXXXX"},
    // { id: "nuke_hut_rush_setup_person4", title: "XXXXX", startingLocation: "XXXXXX", nadeType: "XXXXXXX",
    // throwType: "XXXXX", description: "", map: "XXXXX", contentUrl: "XXXXXXX"},
    // { id: "nuke_hut_rush_setup_person5", title: "XXXXX", startingLocation: "XXXXXX", nadeType: "XXXXXXX",
    // throwType: "XXXXX", description: "", map: "XXXXX", contentUrl: "XXXXXXX"},
    // { id: "nuke_heaven_retake_oneway_utility_set", title: "XXXXX", startingLocation: "XXXXXX", nadeType: "XXXXXXX",
    // throwType: "XXXXX", description: "", map: "XXXXX", contentUrl: "XXXXXXX"},
    { id: "nuke_flash_to_cross_to_secret", title: "Flash to cross secret", startingLocation: "outside", nadeType: "flash",
    throwType: "run", description: "", map: "nuke", contentUrl: "https://streamable.com/l/absc96/mp4.mp4"},
    { id: "nuke_flash_outside_start_of_round", title: "Flash outside", startingLocation: "CT spawn", nadeType: "flash",
    throwType: "run", description: "", map: "nuke", contentUrl: "https://streamable.com/l/2pxt96/mp4.mp4"},
    // { id: "nuke_flash_for_ramp_rush", title: "XXXXX", startingLocation: "XXXXXX", nadeType: "XXXXXXX",
    // throwType: "XXXXX", description: "", map: "XXXXX", contentUrl: "XXXXXXX"},
    { id: "nuke_defensive_ramp_molly", title: "Defensive ramp molly", startingLocation: "ramp", nadeType: "molly",
    throwType: "normal", description: "", map: "nuke", contentUrl: "https://streamable.com/l/jz3hs3/mp4.mp4"},
    // { id: "nuke_flash_a_for_hut_rush", title: "XXXXX", startingLocation: "XXXXXX", nadeType: "XXXXXXX",
    // throwType: "XXXXX", description: "", map: "XXXXX", contentUrl: "XXXXXXX"},
    { id: "nuke_deep_smokewall_pair", title: "Deep smokewall pair", startingLocation: "outside", nadeType: "smoke",
    throwType: "jump", description: "", map: "nuke", contentUrl: "https://streamable.com/l/u43ov9/mp4.mp4"},
    { id: "nuke_cheeky_ramp_smoke", title: "Ramp smoke using gap", startingLocation: "ramp", nadeType: "smoke",
    throwType: "normal", description: "", map: "nuke", contentUrl: "https://streamable.com/l/k739n5/mp4.mp4"},
    { id: "nuke_aleksib_cross_smoke", title: "Cross smoke", startingLocation: "T spawn", nadeType: "smoke",
    throwType: "run", description: "", map: "nuke", contentUrl: "https://streamable.com/l/6ytgay/mp4.mp4"},
    { id: "nuke_a_exec_molly_fake_vent", title: "Molly fake vent", startingLocation: "lobby", nadeType: "molly",
    throwType: "quick run", description: "", map: "nuke", contentUrl: "https://streamable.com/l/6myq1k/mp4.mp4"},
    { id: "nuke_a_exec_heaven_smoke_mustang_molly", title: "Heaven smoke + mustang molly", startingLocation: "silo", nadeType: "smoke, molly",
    throwType: "normal", description: "", map: "nuke", contentUrl: "https://streamable.com/l/1h9sl3/mp4.mp4"},
    // { id: "nuke_a_exec_mini_smoke_door_lineup", title: "XXXXX", startingLocation: "XXXXXX", nadeType: "XXXXXXX",
    // throwType: "XXXXX", description: "", map: "XXXXX", contentUrl: "XXXXXXX"},
    { id: "nuke_a_exec_back_silo_molly_and_flashes", title: "Back silo molly and flashes", startingLocation: "T roof", nadeType: "flash, molly",
    throwType: "jump", description: "", map: "nuke", contentUrl: "https://streamable.com/l/1o6rhn/mp4.mp4"},

  // *********************************************** MIRAGE ***********************************************

    { id: "mirage_easy_smoke_cross_from_top_mid", title: "Cross smoke", startingLocation: "top mid", nadeType: "smoke",
    throwType: "normal", description: "", map: "mirage", contentUrl: "https://streamable.com/l/ai6y3u/mp4.mp4"},
    { id: "mirage_b_retake_smoke_from_market", title: "B retake smoke", startingLocation: "market", nadeType: "smoke",
    throwType: "normal", description: "", map: "mirage", contentUrl: "https://streamable.com/l/3ldmfe/mp4.mp4"},
    { id: "mirage_t_ramp_lurk_smoke", title: "T ramp lurk smoke", startingLocation: "ramp", nadeType: "smoke",
    throwType: "normal", description: "", map: "mirage", contentUrl: "https://streamable.com/l/k32da0/mp4.mp4"},
    { id: "mirage_smoke_top_connector_from_mid", title: "Top connector smoke", startingLocation: "mid", nadeType: "smoke",
    throwType: "quick run", description: "", map: "mirage", contentUrl: "https://streamable.com/l/aooatj/mp4.mp4"},
    { id: "mirage_smoke_top_connector_from_top_mid", title: "Smoke top connector", startingLocation: "top mid", nadeType: "smoke",
    throwType: "jump", description: "", map: "mirage", contentUrl: "https://streamable.com/l/zd0d41/mp4.mp4"},
    { id: "mirage_smoke_top_connector_from_spawn", title: "Smoke top connector", startingLocation: "T spawn", nadeType: "smoke",
    throwType: "crouch+jump", description: "", map: "mirage", contentUrl: "https://streamable.com/l/ykwbo7/mp4.mp4"},
    { id: "mirage_smoke_left_side_arch", title: "Smoke left side arch", startingLocation: "outside back apts", nadeType: "smoke",
    throwType: "jump", description: "", map: "mirage", contentUrl: "https://streamable.com/l/qdpqe0/mp4.mp4"},
    { id: "mirage_smoke_catwalk_rail", title: "Smoke catwalk rail", startingLocation: "T spawn", nadeType: "smoke",
    throwType: "jump", description: "", map: "mirage", contentUrl: "https://streamable.com/l/97a4zm/mp4.mp4"},
    { id: "mirage_smoke_mid_window_from_top_mid_quick", title: "Smoke window (quick)", startingLocation: "top mid", nadeType: "smoke",
    throwType: "run", description: "", map: "mirage", contentUrl: "https://streamable.com/l/p9wlwj/mp4.mp4"},
    { id: "mirage_smoke_mid_window", title: "Smoke window (lineup)", startingLocation: "top mid", nadeType: "smoke",
    throwType: "normal", description: "", map: "mirage", contentUrl: "https://streamable.com/l/eluhea/mp4.mp4"},
    { id: "mirage_smoke_mid_window_from_spawn_alternate", title: "Smoke window from spawn (alternate)", startingLocation: "T spawn", nadeType: "smoke",
    throwType: "jump throw", description: "", map: "mirage", contentUrl: "https://streamable.com/l/nxcj9t/mp4.mp4"}, //this should probably have a new throw category
    { id: "mirage_smoke_market_window", title: "Smoke market window", startingLocation: "apartments", nadeType: "smoke",
    throwType: "jump", description: "", map: "mirage", contentUrl: "https://streamable.com/l/3qee3m/mp4.mp4"},
    { id: "mirage_smoke_market_door", title: "Smoke market door", startingLocation: "apartments", nadeType: "smoke",
    throwType: "jump", description: "", map: "mirage", contentUrl: "https://streamable.com/l/fqk0dl/mp4.mp4"},
    { id: "mirage_smoke_palace_from_outside_market", title: "Smoke palace", startingLocation: "outside market", nadeType: "smoke",
    throwType: "jump", description: "", map: "mirage", contentUrl: "https://streamable.com/l/9n6b0g/mp4.mp4"},
    { id: "mirage_smoke_stairs", title: "Smoke stairs", startingLocation: "ramp", nadeType: "smoke",
    throwType: "normal", description: "", map: "mirage", contentUrl: "https://streamable.com/l/owfmgy/mp4.mp4"},
    { id: "mirage_smoke_right_side_arch", title: "Smoke right side arch", startingLocation: "outside back apts", nadeType: "smoke",
    throwType: "jump", description: "", map: "mirage", contentUrl: "https://streamable.com/l/k60j4n/mp4.mp4"},
    { id: "mirage_smoke_safe_a_ramp", title: "Safe A ramp smoke", startingLocation: "ticket", nadeType: "smoke",
    throwType: "normal", description: "", map: "mirage", contentUrl: "https://streamable.com/l/80rvjf/mp4.mp4"},
    { id: "mirage_smoke_mid_window_alternate", title: "Smoke window", startingLocation: "T spawn", nadeType: "smoke", //which is actually alternate???
    throwType: "run+jump", description: "", map: "mirage", contentUrl: "https://streamable.com/l/1r67xf/mp4.mp4"},
    { id: "mirage_smoke_jungle_from_site", title: "Smoke jungle", startingLocation: "A site", nadeType: "smoke",
    throwType: "normal", description: "", map: "mirage", contentUrl: "https://streamable.com/l/kvcnws/mp4.mp4"},
    { id: "mirage_smoke_jungle", title: "Smoke jungle", startingLocation: "ramp", nadeType: "smoke",
    throwType: "normal", description: "", map: "mirage", contentUrl: "https://streamable.com/l/awtf6f/mp4.mp4"},
    { id: "mirage_smoke_top_mid", title: "Smoke top mid", startingLocation: "T spawn", nadeType: "smoke",
    throwType: "normal", description: "", map: "mirage", contentUrl: "https://streamable.com/l/y0qnzp/mp4.mp4"}, //might wanna get rid of this
    // { id: "mirage_smoke_jungle_from_spawn", title: "XXXXX", startingLocation: "XXXXXX", nadeType: "XXXXXXX",
    // throwType: "XXXXX", description: "", map: "XXXXX", contentUrl: "XXXXXXX"},
    // { id: "mirage_smoke_deep_stairs", title: "XXXXX", startingLocation: "XXXXXX", nadeType: "XXXXXXX",
    // throwType: "XXXXX", description: "", map: "XXXXX", contentUrl: "XXXXXXX"},
    { id: "mirage_smoke_go_catwalk", title: "Run up catwalk smoke", startingLocation: "catwalk", nadeType: "smoke",
    throwType: "right click", description: "", map: "mirage", contentUrl: "https://streamable.com/l/h9mgpu/mp4.mp4"},
    { id: "mirage_smoke_ct_from_site", title: "Smoke CT", startingLocation: "A site", nadeType: "smoke",
    throwType: "normal", description: "", map: "mirage", contentUrl: "https://streamable.com/l/sln3kn/mp4.mp4"},
    { id: "XXXXX", title: "XXXXX", startingLocation: "XXXXXX", nadeType: "XXXXXXX",
    throwType: "XXXXX", description: "", map: "XXXXX", contentUrl: "XXXXXXX"},
    { id: "XXXXX", title: "XXXXX", startingLocation: "XXXXXX", nadeType: "XXXXXXX",
    throwType: "XXXXX", description: "", map: "XXXXX", contentUrl: "XXXXXXX"},
    { id: "XXXXX", title: "XXXXX", startingLocation: "XXXXXX", nadeType: "XXXXXXX",
    throwType: "XXXXX", description: "", map: "XXXXX", contentUrl: "XXXXXXX"},
    { id: "XXXXX", title: "XXXXX", startingLocation: "XXXXXX", nadeType: "XXXXXXX",
    throwType: "XXXXX", description: "", map: "XXXXX", contentUrl: "XXXXXXX"},
    { id: "XXXXX", title: "XXXXX", startingLocation: "XXXXXX", nadeType: "XXXXXXX",
    throwType: "XXXXX", description: "", map: "XXXXX", contentUrl: "XXXXXXX"},
    { id: "XXXXX", title: "XXXXX", startingLocation: "XXXXXX", nadeType: "XXXXXXX",
    throwType: "XXXXX", description: "", map: "XXXXX", contentUrl: "XXXXXXX"},


    // { id: "XXXXX", title: "XXXXX", startingLocation: "XXXXXX", nadeType: "XXXXXXX", 
    // throwType: "XXXXX", description: "", map: "XXXXX", contentUrl: "XXXXXXX"},

]

  // export interface Grenade {
  //   title: string;
  //   startingLocation: string;
  //   nadeType: string;
  //   throwType: string;
  //   description: string;
  //   map: string;
  //   contentUrl: string;
  // }